### ISSUE TITLE
刚开始好好的,一会之后就报这个错(版本:4.1.0)

### ISSUE THREAD

**Issue by Mrshengjie** [codingapi/tx-lcn#138]
事件为:a->CartService.deleteByUserAndProducts
com.ddyk.shop.cart.service.CartService.deleteByUserAndProducts此是我的业务方法.

报错:
[ INFO ] [2018-09-21 14:43:53] com.codingapi.tx.framework.utils.SocketManager [84] - send-msg->{"a":"atg","k":"biyMslbf","p":{"s":0,"t":"SBuTyN9Y","ms":"public int com.ddyk.shop.cart.service.CartService.deleteByUserAndProducts(com.ddyk.shop.common.cart.dto.CartDelUserProduct)","g":"cW76pYmO"}}
[ ERROR] [2018-09-21 14:43:53] org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/cartapi].[dispatcherServlet] [182] - Servlet.service() for servlet [dispatcherServlet] in context with path [/cartapi] threw exception [Request processing failed; nested exception is java.lang.reflect.UndeclaredThrowableException] with root cause
com.lorne.core.framework.exception.ServiceException: update TxGroup error, groupId:cW76pYmO
        at com.codingapi.tx.aop.service.impl.TxRunningTransactionServerImpl.execute(TxRunningTransactionServerImpl.java:89)
        at com.codingapi.tx.aop.service.impl.AspectBeforeServiceImpl.around(AspectBeforeServiceImpl.java:52)
        at com.codingapi.tx.springcloud.interceptor.TxManagerInterceptor.around(TxManagerInterceptor.java:30)
        at com.codingapi.tx.springcloud.interceptor.TransactionAspect.around(TransactionAspect.java:38)
        at sun.reflect.GeneratedMethodAccessor83.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:627)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:616)
        at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:671)
        at com.ddyk.shop.cart.service.CartService$$EnhancerBySpringCGLIB$$c4d2c147.deleteByUserAndProducts(<generated>)
        at com.ddyk.shop.cart.controller.CartController.deleteByUserAndProducts(CartController.java:88)
        at sun.reflect.GeneratedMethodAccessor126.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
        at org.springframework.web.servlet.FrameworkServlet.doDelete(FrameworkServlet.java:894)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:667)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1468)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)

**Comment by Mrshengjie** [comment]
重启a服务后,能正常处理,过一会就又报这个错了.

**Comment by Mrshengjie** [comment]
反复测试,服务开着过了一个晚上,第二天再试几次就不行了.出现同样问题.这是管理端日志:
 DEBUG] [2018-09-27 15:16:15] com.codingapi.tm.netty.handler.TxCoreServerHandler [48] - request->{"a":"cg","k":"3VH3004s","p":{"g":"KssQBIr8"}}
[ DEBUG] [2018-09-27 15:16:16] com.codingapi.tm.netty.handler.TxCoreServerHandler [48] - request->{"a":"plb","k":"TewFHYfY","p":{"d":"e6d0070d6c45b0cd2b01878aa356d39e","g":"MVbZsP8k","k":"20b6f2c846c6669e900f839d99fbd802"}}
[ DEBUG] [2018-09-27 15:16:16] com.codingapi.tm.netty.handler.TxCoreServerHandler [48] - request->{"a":"atg","k":"Iqe4vIdm","p":{"s":0,"t":"P8A5EZDM","ms":"public int com.ddyk.shop.cart.service.CartService.deleteByUserAndProducts(com.ddyk.shop.common.cart.dto.CartDelUserProduct)","g":"MVbZsP8k"}}
[ DEBUG] [2018-09-27 15:16:16] com.codingapi.tm.netty.handler.TxCoreServerHandler [48] - request->{"a":"ctg","k":"iHbVGC97","p":{"s":0,"g":"KssQBIr8"}}

**Comment by Mrshengjie** [comment]
查日志事件源服务发现:
重复快实验中得到:

第1调:
[ DEBUG] [2018-09-29 16:25:32] com.codingapi.tx.aop.service.impl.TxStartTransactionServerImpl [38] - --->begin start transaction
[ INFO ] [2018-09-29 16:25:32] com.codingapi.tx.framework.utils.SocketManager [84] - send-msg->{"a":"cg","k":"uMiEuFc1","p":{"g":"ImSrLwQw"}}
[ DEBUG] [2018-09-29 16:25:32] com.codingapi.tx.netty.handler.TransactionHandler [55] - TxManager-response->{"d":"{\"st\":1538209532155,\"r\":0,\"s\":0,\"nt\":1538209532157,\"g\":\"ImSrLwQw\",\"i\":0,\"o\":0}","k":"uMiEuFc1"}
[ DEBUG] [2018-09-29 16:25:32] com.codingapi.tx.datasource.aspect.DataSourceAspect [32] - getConnection-start---->
[ DEBUG] [2018-09-29 16:25:32] com.codingapi.tx.datasource.AbstractResourceProxy [123] - initLCNConnection
[ DEBUG] [2018-09-29 16:25:32] com.codingapi.tx.datasource.AbstractResourceProxy [129] - lcn datasource transaction control 
[ DEBUG] [2018-09-29 16:25:32] com.codingapi.tx.datasource.AbstractResourceProxy [139] - lcn transaction 
[ INFO ] [2018-09-29 16:25:32] com.codingapi.tx.datasource.relational.LCNStartConnection [62] - transaction is start-connection.
[ INFO ] [2018-09-29 16:25:32] com.codingapi.tx.datasource.relational.LCNStartConnection [70] - lcn start connection init ok .
[ DEBUG] [2018-09-29 16:25:32] com.codingapi.tx.datasource.relational.LCNTransactionDataSource [33] - get new start connection - > ImSrLwQw
[ DEBUG] [2018-09-29 16:25:32] com.codingapi.tx.datasource.aspect.DataSourceAspect [35] - connection-->com.codingapi.tx.datasource.relational.LCNStartConnection@525bf478
[ DEBUG] [2018-09-29 16:25:32] com.codingapi.tx.datasource.aspect.DataSourceAspect [37] - getConnection-end---->
**<font color="#0099ff" size=7 face="黑体">[ INFO ] [2018-09-29 16:25:32] com.codingapi.tx.springcloud.feign.TransactionRestTemplateInterceptor [23] - LCN-SpringCloud TxGroup info -> groupId:ImSrLwQw</font>**
[ INFO ] [2018-09-29 16:25:32] com.codingapi.ribbon.loadbalancer.LcnZoneAwareLoadBalancerProxy [28] - enter chooseServer method, key:null
[ DEBUG] [2018-09-29 16:25:32] com.codingapi.ribbon.loadbalancer.LcnLoadBalancerRule [28] - LCNBalanceProxy - > start
[ DEBUG] [2018-09-29 16:25:32] com.codingapi.ribbon.loadbalancer.LcnLoadBalancerRule [68] - putServer->address->10.0.3.253:8084,md5-->e6d0070d6c45b0cd2b01878aa356d39e
[ DEBUG] [2018-09-29 16:25:32] com.codingapi.tx.aop.bean.TxTransactionLocal [117] - putLoadBalance--> start 
[ INFO ] [2018-09-29 16:25:32] com.codingapi.tx.framework.utils.SocketManager [84] - send-msg->{"a":"plb","k":"wiebFscb","p":{"d":"e6d0070d6c45b0cd2b01878aa356d39e","g":"ImSrLwQw","k":"b400757488f7ceabcb65241d3b944ea4"}}
[ DEBUG] [2018-09-29 16:25:32] com.codingapi.tx.netty.handler.TransactionHandler [55] - TxManager-response->{"d":"1","k":"wiebFscb"}
[ DEBUG] [2018-09-29 16:25:32] com.codingapi.tx.aop.bean.TxTransactionLocal [120] - putLoadBalance--> end
[ DEBUG] [2018-09-29 16:25:32] com.codingapi.ribbon.loadbalancer.LcnLoadBalancerRule [41] - LCNBalanceProxy -> only one server available
[ DEBUG] [2018-09-29 16:25:32] com.codingapi.ribbon.loadbalancer.LcnLoadBalancerRule [56] - LCNBalanceProxy - > end
[ INFO ] [2018-09-29 16:25:32] com.codingapi.tx.datasource.relational.LCNStartConnection [87] - commit label
[ INFO ] [2018-09-29 16:25:32] com.codingapi.tx.framework.utils.SocketManager [84] - send-msg->{"a":"ctg","k":"rnCiH5aA","p":{"s":1,"g":"ImSrLwQw"}}
[ DEBUG] [2018-09-29 16:25:32] com.codingapi.tx.netty.handler.TransactionHandler [55] - TxManager-response->{"d":"1","k":"rnCiH5aA"}
[ DEBUG] [2018-09-29 16:25:32] com.codingapi.tx.aop.service.impl.TxStartTransactionServerImpl [115] - <---end start transaction
[ DEBUG] [2018-09-29 16:25:32] com.codingapi.tx.aop.service.impl.TxStartTransactionServerImpl [116] - start transaction over, res -> groupId:ImSrLwQw, now state:commit
[ DEBUG] [2018-09-29 16:25:32] com.codingapi.tx.springcloud.interceptor.TransactionAspect [31] - annotation-TransactionRunning-end---->
[ DEBUG] [2018-09-29 16:25:32] com.codingapi.tx.springcloud.interceptor.TransactionAspect [29] - annotation-TransactionRunning-start---->
[ DEBUG] [2018-09-29 16:25:32] com.codingapi.tx.aop.service.impl.AspectBeforeServiceImpl [44] - around--> groupId-> null,txTransactionLocal->null



第2次:
[ DEBUG] [2018-09-29 16:25:32] com.codingapi.tx.aop.service.impl.TxStartTransactionServerImpl [38] - --->begin start transaction
[ INFO ] [2018-09-29 16:25:32] com.codingapi.tx.framework.utils.SocketManager [84] - send-msg->{"a":"cg","k":"AADYwnid","p":{"g":"yoz1V3HN"}}
[ DEBUG] [2018-09-29 16:25:32] com.codingapi.tx.netty.handler.TransactionHandler [55] - TxManager-response->{"d":"{\"st\":1538209532664,\"r\":0,\"s\":0,\"nt\":1538209532665,\"g\":\"yoz1V3HN\",\"i\":0,\"o\":0}","k":"AADYwnid"}
[ DEBUG] [2018-09-29 16:25:32] com.codingapi.tx.datasource.aspect.DataSourceAspect [32] - getConnection-start---->
[ DEBUG] [2018-09-29 16:25:32] com.codingapi.tx.datasource.AbstractResourceProxy [123] - initLCNConnection
[ DEBUG] [2018-09-29 16:25:32] com.codingapi.tx.datasource.AbstractResourceProxy [129] - lcn datasource transaction control 
[ DEBUG] [2018-09-29 16:25:32] com.codingapi.tx.datasource.AbstractResourceProxy [139] - lcn transaction 
[ INFO ] [2018-09-29 16:25:32] com.codingapi.tx.datasource.relational.LCNStartConnection [62] - transaction is start-connection.
[ INFO ] [2018-09-29 16:25:32] com.codingapi.tx.datasource.relational.LCNStartConnection [70] - lcn start connection init ok .
[ DEBUG] [2018-09-29 16:25:32] com.codingapi.tx.datasource.relational.LCNTransactionDataSource [33] - get new start connection - > yoz1V3HN
[ DEBUG] [2018-09-29 16:25:32] com.codingapi.tx.datasource.aspect.DataSourceAspect [35] - connection-->com.codingapi.tx.datasource.relational.LCNStartConnection@7d256281
[ DEBUG] [2018-09-29 16:25:32] com.codingapi.tx.datasource.aspect.DataSourceAspect [37] - getConnection-end---->
**<font color="#0099ff" size=7 face="黑体">[ INFO ] [2018-09-29 16:25:32] com.codingapi.tx.springcloud.feign.TransactionRestTemplateInterceptor [23] - LCN-SpringCloud TxGroup info -> groupId:ImSrLwQw</font )**
[ INFO ] [2018-09-29 16:25:32] com.codingapi.ribbon.loadbalancer.LcnZoneAwareLoadBalancerProxy [28] - enter chooseServer method, key:null
[ DEBUG] [2018-09-29 16:25:32] com.codingapi.ribbon.loadbalancer.LcnLoadBalancerRule [28] - LCNBalanceProxy - > start
[ DEBUG] [2018-09-29 16:25:32] com.codingapi.ribbon.loadbalancer.LcnLoadBalancerRule [68] - putServer->address->10.0.3.253:8084,md5-->e6d0070d6c45b0cd2b01878aa356d39e
[ DEBUG] [2018-09-29 16:25:32] com.codingapi.tx.aop.bean.TxTransactionLocal [117] - putLoadBalance--> start 
[ INFO ] [2018-09-29 16:25:32] com.codingapi.tx.framework.utils.SocketManager [84] - send-msg->{"a":"plb","k":"0xDy15FH","p":{"d":"e6d0070d6c45b0cd2b01878aa356d39e","g":"ImSrLwQw","k":"b400757488f7ceabcb65241d3b944ea4"}}
[ DEBUG] [2018-09-29 16:25:32] com.codingapi.tx.netty.handler.TransactionHandler [55] - TxManager-response->{"d":"1","k":"0xDy15FH"}
[ DEBUG] [2018-09-29 16:25:32] com.codingapi.tx.aop.bean.TxTransactionLocal [120] - putLoadBalance--> end
[ DEBUG] [2018-09-29 16:25:32] com.codingapi.ribbon.loadbalancer.LcnLoadBalancerRule [41] - LCNBalanceProxy -> only one server available
[ DEBUG] [2018-09-29 16:25:32] com.codingapi.ribbon.loadbalancer.LcnLoadBalancerRule [56] - LCNBalanceProxy - > end
[ INFO ] [2018-09-29 16:25:32] com.codingapi.tx.datasource.relational.LCNStartConnection [99] - rollback label
[ INFO ] [2018-09-29 16:25:32] com.codingapi.tx.framework.utils.SocketManager [84] - send-msg->{"a":"ctg","k":"jeqHUyes","p":{"s":0,"g":"yoz1V3HN"}}
[ DEBUG] [2018-09-29 16:25:32] com.codingapi.tx.netty.handler.TransactionHandler [55] - TxManager-response->{"d":"0","k":"jeqHUyes"}
[ DEBUG] [2018-09-29 16:25:32] com.codingapi.tx.aop.service.impl.TxStartTransactionServerImpl [115] - <---end start transaction

日志中加粗部分,两次事务既然传了相同的事物组,再几次之后就失败了,原因是redis中的缓存已经被删除了,再发起事物就报错了,之前能过好像是因为redis还没有被清空掉!
