### ISSUE TITLE
关于TXC模式dataSourceProperties注入null导致的异常。

### ISSUE THREAD

**Issue by lynk-coder** [codingapi/tx-lcn#224]
如果配置文件
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tx_manager?useUnicode=true
    username: user
    password: xxxxxxx

没有进行以上的配置，将导致DataSource Bean初始化失败。
具体文件路径
com/codingapi/txlcn/client/core/txc/resource/TxcConfiguration

**Comment by lynk-coder** [comment]
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'compoundJdbcEventListener': Unsatisfied dependency expressed through field 'p6spyEventListener'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'txcJdbcEventListener' defined in class path resource [com/codingapi/txlcn/client/core/txc/resource/TxcConfiguration.class]: Unsatisfied dependency expressed through method 'txcJdbcEventListener' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sqlExecuteInterceptor' defined in class path resource [com/codingapi/txlcn/client/core/txc/resource/TxcConfiguration.class]: Unsatisfied dependency expressed through method 'sqlExecuteInterceptor' parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'txcService' defined in class path resource [com/codingapi/txlcn/client/core/txc/resource/TxcConfiguration.class]: Unsatisfied dependency expressed through method 'txcService' parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'txcExceptionConnectionPool' defined in class path resource [com/codingapi/txlcn/client/core/txc/resource/TxcConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.codingapi.txlcn.client.core.txc.resource.init.TxcExceptionConnectionPool]: Factory method 'txcExceptionConnectionPool' threw exception; nested exception is java.lang.NullPointerException


Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'txcJdbcEventListener' defined in class path resource [com/codingapi/txlcn/client/core/txc/resource/TxcConfiguration.class]: Unsatisfied dependency expressed through method 'txcJdbcEventListener' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sqlExecuteInterceptor' defined in class path resource [com/codingapi/txlcn/client/core/txc/resource/TxcConfiguration.class]: Unsatisfied dependency expressed through method 'sqlExecuteInterceptor' parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'txcService' defined in class path resource [com/codingapi/txlcn/client/core/txc/resource/TxcConfiguration.class]: Unsatisfied dependency expressed through method 'txcService' parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'txcExceptionConnectionPool' defined in class path resource [com/codingapi/txlcn/client/core/txc/resource/TxcConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.codingapi.txlcn.client.core.txc.resource.init.TxcExceptionConnectionPool]: Factory method 'txcExceptionConnectionPool' threw exception; nested exception is java.lang.NullPointerException



Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sqlExecuteInterceptor' defined in class path resource [com/codingapi/txlcn/client/core/txc/resource/TxcConfiguration.class]: Unsatisfied dependency expressed through method 'sqlExecuteInterceptor' parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'txcService' defined in class path resource [com/codingapi/txlcn/client/core/txc/resource/TxcConfiguration.class]: Unsatisfied dependency expressed through method 'txcService' parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'txcExceptionConnectionPool' defined in class path resource [com/codingapi/txlcn/client/core/txc/resource/TxcConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.codingapi.txlcn.client.core.txc.resource.init.TxcExceptionConnectionPool]: Factory method 'txcExceptionConnectionPool' threw exception; nested exception is java.lang.NullPointerException

Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'txcService' defined in class path resource [com/codingapi/txlcn/client/core/txc/resource/TxcConfiguration.class]: Unsatisfied dependency expressed through method 'txcService' parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'txcExceptionConnectionPool' defined in class path resource [com/codingapi/txlcn/client/core/txc/resource/TxcConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.codingapi.txlcn.client.core.txc.resource.init.TxcExceptionConnectionPool]: Factory method 'txcExceptionConnectionPool' threw exception; nested exception is java.lang.NullPointerException


Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'txcExceptionConnectionPool' defined in class path resource [com/codingapi/txlcn/client/core/txc/resource/TxcConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.codingapi.txlcn.client.core.txc.resource.init.TxcExceptionConnectionPool]: Factory method 'txcExceptionConnectionPool' threw exception; nested exception is java.lang.NullPointerException

Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.codingapi.txlcn.client.core.txc.resource.init.TxcExceptionConnectionPool]: Factory method 'txcExceptionConnectionPool' threw exception; nested exception is java.lang.NullPointerException

Caused by: java.lang.NullPointerException: null


以上为部分异常信息

**Comment by D2C-Cai** [comment]
我也是啊，我数据源自己定义的
# spring
spring:
  application:
    name: service-product

  # database
  datasource:
    master:
      jdbc-url: jdbc:mysql://192.168.0.146:3306/shop?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
    slave1:
      jdbc-url: jdbc:mysql://192.168.0.146:3306/shop?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
    slave2:
      jdbc-url: jdbc:mysql://192.168.0.146:3306/shop?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
然后启动一直报错
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'DTXLogicWeaver' defined in URL [jar:file:/C:/Users/Cai/.m2/repository/com/codingapi/txlcn/tx-client/5.0.0.RC1/tx-client-5.0.0.RC1.jar!/com/codingapi/txlcn/client/aspect/weave/DTXLogicWeaver.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'TXLCNTransactionServiceExecutor': Unsatisfied dependency expressed through field 'txLogger'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'defaultTxLogger' defined in URL [jar:file:/C:/Users/Cai/.m2/repository/com/codingapi/txlcn/tx-logger/5.0.0.RC1/tx-logger-5.0.0.RC1.jar!/com/codingapi/txlcn/logger/DefaultTxLogger.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'logDbProperties' defined in URL [jar:file:/C:/Users/Cai/.m2/repository/com/codingapi/txlcn/tx-logger/5.0.0.RC1/tx-logger-5.0.0.RC1.jar!/com/codingapi/txlcn/logger/db/LogDbProperties.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.codingapi.txlcn.logger.db.LogDbProperties]: Constructor threw exception; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:733) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:198) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1266) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1123) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:535) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:495) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:251) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1135) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1062) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:819) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:725) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	... 60 common frames omitted
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'TXLCNTransactionServiceExecutor': Unsatisfied dependency expressed through field 'txLogger'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'defaultTxLogger' defined in URL [jar:file:/C:/Users/Cai/.m2/repository/com/codingapi/txlcn/tx-logger/5.0.0.RC1/tx-logger-5.0.0.RC1.jar!/com/codingapi/txlcn/logger/DefaultTxLogger.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'logDbProperties' defined in URL [jar:file:/C:/Users/Cai/.m2/repository/com/codingapi/txlcn/tx-logger/5.0.0.RC1/tx-logger-5.0.0.RC1.jar!/com/codingapi/txlcn/logger/db/LogDbProperties.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.codingapi.txlcn.logger.db.LogDbProperties]: Constructor threw exception; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:584) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:370) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1336) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:572) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:495) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:251) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1135) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1062) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:819) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:725) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	... 74 common frames omitted
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'defaultTxLogger' defined in URL [jar:file:/C:/Users/Cai/.m2/repository/com/codingapi/txlcn/tx-logger/5.0.0.RC1/tx-logger-5.0.0.RC1.jar!/com/codingapi/txlcn/logger/DefaultTxLogger.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'logDbProperties' defined in URL [jar:file:/C:/Users/Cai/.m2/repository/com/codingapi/txlcn/tx-logger/5.0.0.RC1/tx-logger-5.0.0.RC1.jar!/com/codingapi/txlcn/logger/db/LogDbProperties.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.codingapi.txlcn.logger.db.LogDbProperties]: Constructor threw exception; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:733) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:198) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1266) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1123) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:535) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:495) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:251) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1135) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1062) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:581) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	... 88 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'logDbProperties' defined in URL [jar:file:/C:/Users/Cai/.m2/repository/com/codingapi/txlcn/tx-logger/5.0.0.RC1/tx-logger-5.0.0.RC1.jar!/com/codingapi/txlcn/logger/db/LogDbProperties.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.codingapi.txlcn.logger.db.LogDbProperties]: Constructor threw exception; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:283) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1266) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1123) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:535) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:495) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:251) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1135) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1062) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:819) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:725) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	... 101 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.codingapi.txlcn.logger.db.LogDbProperties]: Constructor threw exception; nested exception is java.lang.NullPointerException
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:182) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:276) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	... 114 common frames omitted
Caused by: java.lang.NullPointerException: null
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:307) ~[na:1.8.0_91]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_91]
	at com.zaxxer.hikari.HikariConfig.setDriverClassName(HikariConfig.java:494) ~[HikariCP-2.7.9.jar:na]
	at com.codingapi.txlcn.logger.db.LogDbProperties.<init>(LogDbProperties.java:40) ~[tx-logger-5.0.0.RC1.jar:5.0.0.RC1]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_91]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_91]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_91]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_91]
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:170) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	... 116 common frames omitted

**Comment by ujued** [comment]
好的，下个版本将彻底解决这个问题。请手动实例化DataSourceProperties，继续流畅体验TX-LCN。-_-

**Comment by D2C-Cai** [comment]
@Bean
    @Primary
    public DataSourceProperties dataSourceProperties() {
        return new DataSourceProperties();
    }

我这样还是不行啊

**Comment by D2C-Cai** [comment]
# tx-lcn
tx-lcn:
  client:
    manager-address: 192.168.0.146:8070
    resource-order: 0
  logger:
    enabled: false
  message:
    netty:
      wait-time: 5
  springcloud:
    loadbalance:
      enabled: true
