### ISSUE TITLE
5.0.2版本 报null错误

### ISSUE THREAD

**Issue by amogege** [codingapi/tx-lcn#266]
5.0.2版本 这个com.codingapi.txlcn.tc.core.transaction.txc.analy.PrimaryKeyListVisitor.newKeyValues 有问题

****************************************错误信息****************************
2019-02-26 18:00:42.087 [http-nio-8730-exec-4] DEBUG com.codingapi.txlcn.tracing.Tracings -
				tracing apply group:8214dc5c2c537, app map:e30=
2019-02-26 18:00:42.088 [http-nio-8730-exec-4] DEBUG com.codingapi.txlcn.tc.aspect.weave.DTXLogicWeaver -
				<---- TxLcn start ---->
2019-02-26 18:00:42.088 [http-nio-8730-exec-4] DEBUG c.c.txlcn.tc.core.context.DefaultGlobalContext -
				Start TxContext[8214dc5c2c537]
2019-02-26 18:00:42.088 [http-nio-8730-exec-4] DEBUG com.codingapi.txlcn.tc.core.DTXServiceExecutor -
				pre business code, unit type: txc @group(8214dc5c2c537)
2019-02-26 18:00:42.089 [http-nio-8730-exec-4] INFO  c.s.cockroach.common.log.ControllerLogAspect -
				{"Ip:":"192.168.238.1","Args":"{\"userAge\":10,\"userAlias\":\"账号\",\"userMobile\":\"手机号\",\"userName\":\"名称\"}","User":"","Title":"接收请求报文","RequestTime":1551175242088,"Uri":"/ms/api/v1/user/lcn/userInfoApi/save","Url":"http://192.168.238.1:8730/ms/api/v1/user/lcn/userInfoApi/save"}
2019-02-26 18:00:42.089 [http-nio-8730-exec-4] INFO  c.s.d.f.user.controller.lcn.LcnTUserInfoController -
				LcnTUserInfoController.save方法。。。
2019-02-26 18:00:42.090 [http-nio-8730-exec-4] DEBUG c.c.txlcn.tc.aspect.weave.DTXResourceWeaver -
				proxy a sql connection: com.codingapi.txlcn.tc.support.p6spy.wrapper.ConnectionWrapper@32897cf7.
2019-02-26 18:00:42.090 [http-nio-8730-exec-4] DEBUG c.s.d.f.user.dao.TUserInfoDao.insertSelective -
				==>  Preparing: INSERT INTO t_user_info ( user_id,user_alias,user_name,user_mobile,enable_flag ) VALUES( ?,?,?,?,? ) 
2019-02-26 18:00:42.090 [http-nio-8730-exec-4] DEBUG c.s.d.f.user.dao.TUserInfoDao.insertSelective -
				==> Parameters: -3085913663202946737(Long), 账号(String), 名称(String), 手机号(String), -3085913663202946737(Long)
2019-02-26 18:00:42.091 [http-nio-8730-exec-4] DEBUG c.c.t.t.c.t.txc.resource.TxcJdbcEventListener -
				statement > INSERT INTO t_user_info (user_id, user_alias, user_name, user_mobile, enable_flag) VALUES (-3085913663202946737, '账号', '名称', '手机号', -3085913663202946737)
2019-02-26 18:00:42.094 [http-nio-8730-exec-4] DEBUG c.c.txlcn.tc.core.context.DefaultGlobalContext -
				cache hit! table t_user_info's struct.
2019-02-26 18:00:44.993 [http-nio-8730-exec-4] DEBUG c.c.t.tc.support.p6spy.wrapper.ConnectionWrapper -
				transaction type[txc] proxy connection:com.codingapi.txlcn.tc.support.p6spy.wrapper.ConnectionWrapper@32897cf7 closed.
2019-02-26 18:00:44.993 [http-nio-8730-exec-4] ERROR c.s.cockroach.common.log.ControllerLogAspect -
				{"Ip:":"192.168.238.1","Args":"{\"userAge\":10,\"userAlias\":\"账号\",\"userMobile\":\"手机号\",\"userName\":\"名称\"}","User":"","ExceptionTime":1551175244993,"Title":"请求处理异常","RequestTime":1551175242088,"ExceptionMsg":"nested exception is org.apache.ibatis.exceptions.PersistenceException: \r\n### Error updating database.  Cause: java.lang.NullPointerException\r\n### The error may involve com.servingcloud.demo.finance.user.dao.TUserInfoDao.insertSelective-Inline\r\n### The error occurred while setting parameters\r\n### SQL: INSERT INTO t_user_info  ( user_id,user_alias,user_name,user_mobile,enable_flag ) VALUES( ?,?,?,?,? )\r\n### Cause: java.lang.NullPointerException","SpendTime":2905,"Uri":"/ms/api/v1/user/lcn/userInfoApi/save","Url":"http://192.168.238.1:8730/ms/api/v1/user/lcn/userInfoApi/save"}
2019-02-26 18:00:44.994 [http-nio-8730-exec-4] ERROR com.codingapi.txlcn.tc.core.DTXServiceExecutor -
				business code error @group(8214dc5c2c537)
2019-02-26 18:00:44.994 [http-nio-8730-exec-4] DEBUG c.c.t.t.c.t.txc.control.TxcRunningTransaction -
				txc > running > clean transaction.
2019-02-26 18:00:44.994 [http-nio-8730-exec-4] DEBUG c.c.t.tc.core.template.TransactionCleanTemplate -
				clean transaction @group(8214dc5c2c537)
2019-02-26 18:00:44.995 [http-nio-8730-exec-4] DEBUG c.c.t.tc.core.template.TransactionCleanTemplate -
				clean transaction over @group(8214dc5c2c537)
2019-02-26 18:00:44.995 [http-nio-8730-exec-4] DEBUG c.c.txlcn.tc.core.context.DefaultGlobalContext -
				Destroy TxContext[8214dc5c2c537]
2019-02-26 18:00:44.995 [http-nio-8730-exec-4] DEBUG com.codingapi.txlcn.tc.core.DTXLocalContext -
				clean thread local[DTXLocalContext]: DTXLocalContext(transactionType=txc, groupId=8214dc5c2c537, unitId=a837b3689b03487666368fd313d1cc41, resource=HikariProxyConnection@847871223 wrapping com.zaxxer.hikari.pool.ProxyConnection.ClosedConnection, destroy=true, inGroup=false, attachment=null, sysTransactionState=1, userTransactionState=-1, proxy=true, justNow=false, proxyTmp=true)
2019-02-26 18:00:44.995 [pool-3-thread-4] DEBUG c.c.txlcn.tc.corelog.aspect.AsyncH2DBAspectLogger -
				async clear aspect log. result:false, groupId: 8214dc5c2c537, used time: 0ms
2019-02-26 18:00:44.996 [http-nio-8730-exec-4] DEBUG com.codingapi.txlcn.tc.aspect.weave.DTXLogicWeaver -
				<---- TxLcn end ---->
2019-02-26 18:00:44.996 [http-nio-8730-exec-4] ERROR o.a.c.c.C.[.[localhost].[/].[dispatcherServlet] -
				Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Cause: java.lang.NullPointerException] with root cause
java.lang.NullPointerException: null
	at com.codingapi.txlcn.tc.core.transaction.txc.analy.PrimaryKeyListVisitor.newKeyValues(PrimaryKeyListVisitor.java:80)
	at com.codingapi.txlcn.tc.core.transaction.txc.analy.PrimaryKeyListVisitor.visit(PrimaryKeyListVisitor.java:60)
	at net.sf.jsqlparser.expression.operators.relational.ExpressionList.accept(ExpressionList.java:58)
	at com.codingapi.txlcn.tc.core.transaction.txc.analy.TxcSqlExecuteInterceptor.postInsert(TxcSqlExecuteInterceptor.java:152)
	at com.codingapi.txlcn.tc.core.transaction.txc.resource.TxcJdbcEventListener.onAfterExecute(TxcJdbcEventListener.java:81)
	at com.codingapi.txlcn.tc.core.transaction.txc.resource.CompoundJdbcEventListener.onAfterExecute(CompoundJdbcEventListener.java:93)
	at com.codingapi.txlcn.tc.support.p6spy.wrapper.PreparedStatementWrapper.execute(PreparedStatementWrapper.java:358)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:59)
	at com.sun.proxy.$Proxy194.execute(Unknown Source)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:46)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74)
	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:50)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:63)
	at com.sun.proxy.$Proxy193.update(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:198)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:185)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
	at com.sun.proxy.$Proxy139.insert(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:278)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:58)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:59)
	at com.sun.proxy.$Proxy141.insertSelective(Unknown Source)
	at com.servingcloud.cockroach.data.service.BaseServiceImpl.add(BaseServiceImpl.java:39)
	at com.servingcloud.demo.finance.user.controller.lcn.LcnTUserInfoController.save(LcnTUserInfoController.java:45)
	at com.servingcloud.demo.finance.user.controller.lcn.LcnTUserInfoController$$FastClassBySpringCGLIB$$562cbf1f.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:56)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:174)
	at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:55)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:174)
	at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:62)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:174)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
	at com.codingapi.txlcn.tc.core.DTXLocalControl.doBusinessCode(DTXLocalControl.java:44)
	at com.codingapi.txlcn.tc.core.DTXServiceExecutor.transactionRunning(DTXServiceExecutor.java:91)
	at com.codingapi.txlcn.tc.aspect.weave.DTXLogicWeaver.runTransaction(DTXLogicWeaver.java:96)
	at com.codingapi.txlcn.tc.aspect.TransactionAspect.runWithTxcTransaction(TransactionAspect.java:103)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:174)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at com.servingcloud.demo.finance.user.controller.lcn.LcnTUserInfoController$$EnhancerBySpringCGLIB$$1af01fec.save(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:877)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:783)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:877)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:851)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:90)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:155)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:123)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:108)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:800)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1471)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
2019-02-26 18:00:44.999 [http-nio-8730-exec-4] DEBUG com.codingapi.txlcn.tracing.Tracings -
				tracing apply group:8214dc5c2c537, app map:e30=
**********************************************************************************

**Comment by 1991wangliang** [comment]
t_user_info 表是如何创建的？

**Comment by 17369644** [comment]
我也遇到这个问题不知道怎么解决
