### ISSUE TITLE
NettyClientRetryHandler - exception

### ISSUE THREAD

**Issue by shenyuewang** [codingapi/tx-lcn#268]
日志文件如下：
io.netty.handler.codec.DecoderException: com.codingapi.txlcn.common.exception.SerializerException: java.lang.ClassNotFoundException: org.springframework.data.redis.RedisSystemException
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98) ~[netty-codec-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [netty-codec-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [netty-codec-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:628) [netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:563) [netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:480) [netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442) [netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [netty-common-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.29.Final.jar:4.1.29.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_201]
Caused by: com.codingapi.txlcn.common.exception.SerializerException: java.lang.ClassNotFoundException: org.springframework.data.redis.RedisSystemException
	at com.codingapi.txlcn.common.util.serializer.ProtostuffSerializer.deSerialize(ProtostuffSerializer.java:99) ~[txlcn-common-5.0.2.RELEASE.jar:5.0.2.RELEASE]
	at com.codingapi.txlcn.common.util.serializer.SerializerContext.deSerialize(SerializerContext.java:61) ~[txlcn-common-5.0.2.RELEASE.jar:5.0.2.RELEASE]
	at com.codingapi.txlcn.txmsg.netty.handler.ObjectSerializerDecoder.decode(ObjectSerializerDecoder.java:41) ~[txlcn-txmsg-netty-5.0.2.RELEASE.jar:5.0.2.RELEASE]
	at com.codingapi.txlcn.txmsg.netty.handler.ObjectSerializerDecoder.decode(ObjectSerializerDecoder.java:31) ~[txlcn-txmsg-netty-5.0.2.RELEASE.jar:5.0.2.RELEASE]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[netty-codec-4.1.29.Final.jar:4.1.29.Final]
	... 20 common frames omitted
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: org.springframework.data.redis.RedisSystemException
	at io.protostuff.runtime.RuntimeEnv.loadClass(RuntimeEnv.java:258) ~[protostuff-runtime-1.6.0.jar:1.6.0]
	at io.protostuff.runtime.DefaultIdStrategy.getSchemaWrapper(DefaultIdStrategy.java:185) ~[protostuff-runtime-1.6.0.jar:1.6.0]
	at io.protostuff.runtime.DefaultIdStrategy.resolvePojoFrom(DefaultIdStrategy.java:524) ~[protostuff-runtime-1.6.0.jar:1.6.0]
	at io.protostuff.runtime.PolymorphicThrowableSchema.readObjectFrom(PolymorphicThrowableSchema.java:205) ~[protostuff-runtime-1.6.0.jar:1.6.0]
	at io.protostuff.runtime.ObjectSchema.readObjectFrom(ObjectSchema.java:678) ~[protostuff-runtime-1.6.0.jar:1.6.0]
	at io.protostuff.runtime.ObjectSchema.mergeFrom(ObjectSchema.java:350) ~[protostuff-runtime-1.6.0.jar:1.6.0]
	at io.protostuff.CodedInput.mergeObjectEncodedAsGroup(CodedInput.java:359) ~[protostuff-core-1.6.0.jar:1.6.0]
	at io.protostuff.CodedInput.mergeObject(CodedInput.java:321) ~[protostuff-core-1.6.0.jar:1.6.0]
	at io.protostuff.runtime.RuntimeUnsafeFieldFactory$15$1.mergeFrom(RuntimeUnsafeFieldFactory.java:1217) ~[protostuff-runtime-1.6.0.jar:1.6.0]
	at io.protostuff.runtime.RuntimeSchema.mergeFrom(RuntimeSchema.java:466) ~[protostuff-runtime-1.6.0.jar:1.6.0]
	at io.protostuff.CodedInput.mergeObjectEncodedAsGroup(CodedInput.java:359) ~[protostuff-core-1.6.0.jar:1.6.0]
	at io.protostuff.CodedInput.mergeObject(CodedInput.java:321) ~[protostuff-core-1.6.0.jar:1.6.0]
	at io.protostuff.runtime.RuntimeUnsafeFieldFactory$13$1.mergeFrom(RuntimeUnsafeFieldFactory.java:1038) ~[protostuff-runtime-1.6.0.jar:1.6.0]
	at io.protostuff.runtime.RuntimeSchema.mergeFrom(RuntimeSchema.java:466) ~[protostuff-runtime-1.6.0.jar:1.6.0]
	at io.protostuff.IOUtil.mergeFrom(IOUtil.java:77) ~[protostuff-core-1.6.0.jar:1.6.0]
	at io.protostuff.ProtostuffIOUtil.mergeFrom(ProtostuffIOUtil.java:122) ~[protostuff-core-1.6.0.jar:1.6.0]
	at com.codingapi.txlcn.common.util.serializer.ProtostuffSerializer.deSerialize(ProtostuffSerializer.java:96) ~[txlcn-common-5.0.2.RELEASE.jar:5.0.2.RELEASE]
	... 24 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.springframework.data.redis.RedisSystemException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[na:1.8.0_201]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_201]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[na:1.8.0_201]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_201]
	at io.protostuff.runtime.RuntimeEnv.loadClass(RuntimeEnv.java:251) ~[protostuff-runtime-1.6.0.jar:1.6.0]
	... 40 common frames omitted

**Comment by shenyuewang** [comment]
追加个问题：
com.codingapi.txlcn.txmsg.exception.RpcException: request fail. non tx-manager is alive.
我确定tx-manager是启动的。

**Comment by ujued** [comment]
单实例的情况下：TC与TM断开连接超过 8 × 6000毫秒后，再启动TM无效。目前TC无法感知
