### ISSUE TITLE
txc模式报错java.sql.SQLException: java.sql.SQLException: ORA-00936: 缺失表达式

### ISSUE THREAD

**Issue by lingzihan1215** [codingapi/tx-lcn#270]
- I have searched the [issues](https://github.com/codingapi/tx-lcn/issues) of this repository and believe that this is not a duplicate.

### 1. Bug Description
被调用方txc模式，报错java.sql.SQLException: java.sql.SQLException: ORA-00936: 缺失表达式

### 2. Environment:
- JDK version:1.8
- OS:win7
- TX-LCN version:5.0.1
- Others:

### 3. Exception Stacktrace

```
2019-02-28 15:40:11.656 qtp871557892-51 DEBUG com.codingapi.txlcn.tc.core.transaction.txc.resource.TxcJdbcEventListener - statement > UPDATE appmodule_function SET create_by = 5000, create_date = '2019-01-23T21:25:24.327+0800', last_modified_by = 5000, last_modified_date = '2019-02-28T15:40:11.623+0800', last_modified_version = 13, app_module_id = NULL, code = '008801', description = NULL, enabled = true, layout = 8899, name = '分布式事务测试', iorder = 1, parent_id = NULL, url = NULL WHERE id = 8899 AND last_modified_version = 12
    2019-02-28 15:40:13.389 qtp871557892-51 INFO p6spy - statement|0|41ms|SELECT appmodule_function.create_by, appmodule_function.create_date, appmodule_function.last_modified_by, appmodule_function.last_modified_date, appmodule_function.last_modified_version, appmodule_function.app_module_id, appmodule_function.code, appmodule_function.description, appmodule_function.enabled, appmodule_function.layout, appmodule_function.name, appmodule_function.iorder, appmodule_function.parent_id, appmodule_function.url, FROM appmodule_function WHERE id = 8899 AND last_modified_version = 12
    2019-02-28 15:40:13.389 qtp871557892-51 INFO p6spy - com.crux.appmodule.appfunction.AppFunctionServiceImpl$$EnhancerBySpringCGLIB$$f8924de7.save(:-1)
    2019-02-28 15:40:13.394 qtp871557892-51 DEBUG org.hibernate.engine.jdbc.spi.SqlExceptionHelper - could not execute statement [n/a]
    java.sql.SQLException: java.sql.SQLException: ORA-00936: 缺失表达式
    Query: SELECT appmodule_function.create_by, appmodule_function.create_date, appmodule_function.last_modified_by, appmodule_function.last_modified_date, appmodule_function.last_modified_version, appmodule_function.app_module_id, appmodule_function.code, appmodule_function.description, appmodule_function.enabled, appmodule_function.layout, appmodule_function.name, appmodule_function.iorder, appmodule_function.parent_id, appmodule_function.url, FROM appmodule_function WHERE id = 8899 AND last_modified_version = 12 Parameters: []
    at com.codingapi.txlcn.tc.core.transaction.txc.analy.TxcSqlExecuteInterceptor.preUpdate(TxcSqlExecuteInterceptor.java:98)
    at com.codingapi.txlcn.tc.core.transaction.txc.resource.TxcJdbcEventListener.onBeforeAnyExecute(TxcJdbcEventListener.java:63)
    at com.codingapi.txlcn.tc.support.p6spy.event.P6spyJdbcEventListener.onBeforeExecuteUpdate(P6spyJdbcEventListener.java:92)
    at com.codingapi.txlcn.tc.core.transaction.txc.resource.CompoundJdbcEventListener.onBeforeExecuteUpdate(CompoundJdbcEventListener.java:123)
    at com.codingapi.txlcn.tc.support.p6spy.wrapper.PreparedStatementWrapper.executeUpdate(PreparedStatementWrapper.java:82)
    at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:175)
    at org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:3217)
    at org.hibernate.persister.entity.AbstractEntityPersister.updateOrInsert(AbstractEntityPersister.java:3090)
    at org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:3491)
Paste your Exception Stacktrace here!
```

### 4. Tour Idea
看了下源码，好像是这个地方引起的
![image](https://user-images.githubusercontent.com/7507599/53625829-1d148100-3c3f-11e9-926c-238768c3e419.png)

**Comment by 1991wangliang** [comment]
请参考模板提供相应的描述，不然我们无从响应你们的问题。

**Comment by lingzihan1215** [comment]
修改了issue的格式，望关注下，多谢大牛！！

**Comment by ujued** [comment]
谢谢，确认是bug。不过需要注意的是，TXC模式要求每个数据表都要有主键

**Comment by lingzihan1215** [comment]
多谢回复。
