### ISSUE TITLE
txlcn-tc在maven install时报错

### ISSUE THREAD

**Issue by exploreing** [codingapi/tx-lcn#278]
2019-03-05 14:35:22.334  INFO 1052 --- [ntLoopGroup-3-3] c.c.t.t.n.i.NettyRpcClientInitializer    : Try connect socket(/127.0.0.1:7970) - count 1
2019-03-05 14:35:22.378  INFO 1052 --- [    Thread-1032] c.c.t.tc.txmsg.TCSideRpcInitCallBack     : Send init message to TM[/127.0.0.1:7970]
2019-03-05 14:35:22.402 ERROR 1052 --- [ntLoopGroup-3-4] c.c.t.t.n.h.NettyClientRetryHandler      : keepSize:1,nowSize:0
2019-03-05 14:35:22.402 ERROR 1052 --- [ntLoopGroup-3-4] c.c.t.t.n.h.NettyClientRetryHandler      : socketAddress:/127.0.0.1:7970 
2019-03-05 14:35:22.402  INFO 1052 --- [ntLoopGroup-3-4] c.c.t.t.n.i.NettyRpcClientInitializer    : Try connect socket(/127.0.0.1:7970) - count 1
2019-03-05 14:35:22.405  INFO 1052 --- [    Thread-1033] c.c.t.tc.txmsg.TCSideRpcInitCallBack     : Send init message to TM[/127.0.0.1:7970]
Exception in thread "Thread-1033" java.util.NoSuchElementException
	at java.util.LinkedList.getFirst(LinkedList.java:244)
	at com.codingapi.txlcn.txmsg.netty.bean.RpcCmdContext.findRpcContent(RpcCmdContext.java:99)
	at com.codingapi.txlcn.txmsg.netty.bean.RpcCmdContext.createRpcContent(RpcCmdContext.java:119)
	at com.codingapi.txlcn.txmsg.netty.bean.RpcCmdContext.addKey(RpcCmdContext.java:86)
	at com.codingapi.txlcn.txmsg.netty.bean.NettyRpcCmd.randomKey(NettyRpcCmd.java:43)
	at com.codingapi.txlcn.txmsg.netty.impl.NettyRpcClient.request(NettyRpcClient.java:79)
	at com.codingapi.txlcn.tc.txmsg.TCSideRpcInitCallBack.lambda$connected$2(TCSideRpcInitCallBack.java:78)
	at java.lang.Thread.run(Thread.java:748)
2019-03-05 14:35:25.257 ERROR 1052 --- [     Thread-793] c.c.t.tc.txmsg.TCSideRpcInitCallBack     : Send init message exception: request timeout.. connect fail!
2019-03-05 14:35:25.298 ERROR 1052 --- [     Thread-794] c.c.t.tc.txmsg.TCSideRpcInitCallBack     : Send init message exception: request timeout.. connect fail!
2019-03-05 14:35:25.321 ERROR 1052 --- [     Thread-795] c.c.t.tc.txmsg.TCSideRpcInitCallBack     : Send init message exception: request timeout.. connect fail!
2019-03-05 14:35:25.334 ERROR 1052 --- [     Thread-796] c.c.t.tc.txmsg.TCSideRpcInitCallBack     : Send init message exception: request timeout.. connect fail!
2019-03-05 14:35:25.344 ERROR 1052 --- [     Thread-797] c.c.t.tc.txmsg.TCSideRpcInitCallBack     : Send init message exception: request timeout.. connect fail!
2019-03-05 14:35:25.368 ERROR 1052 --- [     Thread-798] c.c.t.tc.txmsg.TCSideRpcInitCallBack     : Send init message exception: request timeout.. connect fail!
2019-03-05 14:35:25.382 ERROR 1052 --- [     Thread-799] c.c.t.tc.txmsg.TCSideRpcInitCallBack     : Send init message exception: request timeout.. connect fail!
2019-03-05 14:35:25.392 ERROR 1052 --- [     Thread-800] c.c.t.tc.txmsg.TCSideRpcInitCallBack     : Send init message exception: request timeout.. connect fail!
2019-03-05 14:35:25.397 ERROR 1052 --- [     Thread-801] c.c.t.tc.txmsg.TCSideRpcInitCallBack     : Send init message exception: request timeout.. connect fail!
2019-03-05 14:35:25.406 ERROR 1052 --- [     Thread-802] c.c.t.tc.txmsg.TCSideRpcInitCallBack     : Send init message exception: request timeout.. connect fail!
2019-03-05 14:35:25.414 ERROR 1052 --- [     Thread-803] c.c.t.tc.txmsg.TCSideRpcInitCallBack     : Send init message exception: request timeout.. connect fail!
2019-03-05 14:35:25.422 ERROR 1052 --- [     Thread-804] c.c.t.tc.txmsg.TCSideRpcInitCallBack     : Send init message exception: request timeout.. connect fail!
2019-03-05 14:35:25.433 ERROR 1052 --- [     Thread-805] c.c.t.tc.txmsg.TCSideRpcInitCallBack     : Send init message exception: request timeout.. connect fail!
2019-03-05 14:35:25.448 ERROR 1052 --- [     Thread-806] c.c.t.tc.txmsg.TCSideRpcInitCallBack     : Send init message exception: request timeout.. connect fail!

麻烦能帮看一下是什么问题吗，txlcn-tc模块一直maven install不成功

**Comment by ujued** [comment]
这个地方的单元测试依赖TM。两种解决方案：
1. 跳过单元测试安装
2. 启动TM并绑定在打包机器的127.0.0.1:8090

**Comment by liulei008** [comment]
我在启动的时候报错了 这个怎么解决
