### ISSUE TITLE
tc 报 ClassNotFoundException

### ISSUE THREAD

**Issue by helei810304** [codingapi/tx-lcn#300]
今天跑demo ，报了这个异常
	at com.codingapi.txlcn.common.util.serializer.ProtostuffSerializer.deSerialize(ProtostuffSerializer.java:96) ~[txlcn-common-5.0.2.RELEASE.jar:5.0.2.RELEASE]
	... 24 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.springframework.data.redis.serializer.SerializationException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_111]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_111]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[na:1.8.0_111]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_111]

出错在这行com.codingapi.txlcn.common.util.serializer.ProtostuffSerializer.deSerialize(ProtostuffSerializer.java:96) ~[txlcn-common-5.0.2.RELEASE.jar:5.0.2.RELEASE]

client 端还会去连redis 么，之前是没有的

**Comment by ujued** [comment]
好的谢谢！#268
