### ISSUE TITLE
V5.0.1  TXC模式  PrimaryKeyListVisitor.newKeyValues   NullPointerException

### ISSUE THREAD

**Issue by i-tudou** [codingapi/tx-lcn#321]
- [ ] I have searched the [issues](https://github.com/codingapi/tx-lcn/issues) of this repository and believe that this is not a duplicate.

### 1. Bug Description

PrimaryKeyListVisitor.newKeyValues   NullPointerException
expressions.get(i)   获取的对象node为null，导致  expressions.get(i).getASTNode().jjtGetValue()  报空指针异常，不知道是不是我配置的事。

以及PrimaryKeysProvider是否必须需要实现？

### 2. Environment:
- JDK version: 1.8
- OS: 
- TX-LCN version: 5.0.1
- Others:   spring boot 1.5.x

### 3. Exception Stacktrace
```
Caused by: org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: java.lang.NullPointerException
### The error may involve com.itudou.txlcn.txlcncommon.dao.TxlcnDemoMapper.insert-Inline
### The error occurred while setting parameters
### SQL: insert into txlcn_demo (id, kid, demo_field,        group_id, unit_id, app_name,        create_by, create_date, update_by,        update_date, remarks, del_flag       )     values (?, ?, ?,        ?, ?, ?,        ?, ?, ?,        ?, ?, ?       )
### Cause: java.lang.NullPointerException
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30) ~[mybatis-3.4.0.jar:3.4.0]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:200) ~[mybatis-3.4.0.jar:3.4.0]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:185) ~[mybatis-3.4.0.jar:3.4.0]
	at sun.reflect.GeneratedMethodAccessor140.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java) ~[na:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:434) ~[mybatis-spring-1.3.0.jar:1.3.0]
	... 110 common frames omitted
Caused by: java.lang.NullPointerException: null
	at com.codingapi.txlcn.tc.core.transaction.txc.analy.PrimaryKeyListVisitor.newKeyValues(PrimaryKeyListVisitor.java:80) ~[txlcn-tc-5.0.1.RELEASE.jar:5.0.1.RELEASE]
	at com.codingapi.txlcn.tc.core.transaction.txc.analy.PrimaryKeyListVisitor.visit(PrimaryKeyListVisitor.java:60) ~[txlcn-tc-5.0.1.RELEASE.jar:5.0.1.RELEASE]
	at net.sf.jsqlparser.expression.operators.relational.ExpressionList.accept(ExpressionList.java:58) ~[jsqlparser-1.3.jar:na]
	at com.codingapi.txlcn.tc.core.transaction.txc.analy.TxcSqlExecuteInterceptor.postInsert(TxcSqlExecuteInterceptor.java:152) ~[txlcn-tc-5.0.1.RELEASE.jar:5.0.1.RELEASE]
	at com.codingapi.txlcn.tc.core.transaction.txc.resource.TxcJdbcEventListener.onAfterExecute(TxcJdbcEventListener.java:81) ~[txlcn-tc-5.0.1.RELEASE.jar:5.0.1.RELEASE]
	at com.codingapi.txlcn.tc.core.transaction.txc.resource.CompoundJdbcEventListener.onAfterExecute(CompoundJdbcEventListener.java:93) ~[txlcn-tc-5.0.1.RELEASE.jar:5.0.1.RELEASE]
	at com.codingapi.txlcn.tc.support.p6spy.wrapper.PreparedStatementWrapper.execute(PreparedStatementWrapper.java:358) ~[txlcn-tc-5.0.1.RELEASE.jar:5.0.1.RELEASE]
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:46) ~[mybatis-3.4.0.jar:3.4.0]
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74) ~[mybatis-3.4.0.jar:3.4.0]
	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:50) ~[mybatis-3.4.0.jar:3.4.0]
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117) ~[mybatis-3.4.0.jar:3.4.0]
	at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76) ~[mybatis-3.4.0.jar:3.4.0]
	at sun.reflect.GeneratedMethodAccessor141.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java) ~[na:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:63) ~[mybatis-3.4.0.jar:3.4.0]
	at com.sun.proxy.$Proxy180.update(Unknown Source) ~[na:na]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:198) ~[mybatis-3.4.0.jar:3.4.0]
	... 115 common frames omitted

```
Paste your Exception Stacktrace here!
```

### 4. Tour Idea

**Comment by i-tudou** [comment]
@ujued 

TXC-Lcn，TXC模式下：
主键为`bigint`，程序维护主键，插入的时候：
`PrimaryKeyListVisitor` 类
```
private Map<String, Object> newKeyValues(List<Expression> expressions) {
        Map<String, Object> keyValues = new HashMap<>();
        for (int i = 0; i < columns.size(); i++) {
            columns.get(i).setTable(table);
            if (primaryKeys.contains(columns.get(i).getFullyQualifiedName())) {
                Object expression = expressions.get(i).getASTNode().jjtGetValue();
                keyValues.put(columns.get(i).getFullyQualifiedName(),
                        Reflection.invokeN(expression.getClass(), "getValue", expression, new Object[0]));
            }
        }
        return keyValues;
    }
```
`expressions.get(i).getASTNode()` 这段代码为`null`  

jsqlparser 的 CCJSqlParser

![image](https://user-images.githubusercontent.com/30862119/54797289-7562ff80-4c8e-11e9-94b2-0b427986ca1f.png)
![image](https://user-images.githubusercontent.com/30862119/54797392-f02c1a80-4c8e-11e9-9e7d-fad78a0e721b.png)

**Comment by DeclanWang** [comment]
@i-tudou 我这边是用了比较粗暴的方法：
`    private Map<String, Object> newKeyValues(List<Expression> expressions) {
        Map<String, Object> keyValues = new HashMap<>();
        for (int i = 0; i < columns.size(); i++) {
            columns.get(i).setTable(table);
            if (primaryKeys.contains(columns.get(i).getFullyQualifiedName())) {
                SimpleNode node = expressions.get(i).getASTNode();
                if (Objects.nonNull(node)) {
                    Object expression = node.jjtGetValue();
                    keyValues.put(columns.get(i).getFullyQualifiedName(),
                            Reflection.invokeN(expression.getClass(), "getValue", expression, new Object[0]));
                } else {
                    String strValue = expressions.get(i).toString();
                    if (Objects.nonNull(strValue)) {
                        try {
                            Long longValue = Long.valueOf(strValue);
                            keyValues.put(columns.get(i).getFullyQualifiedName(), longValue);
                        } catch (NumberFormatException e) {
                            keyValues.put(columns.get(i).getFullyQualifiedName(), strValue);
                        }
                    }
                }
            }
        }
        return keyValues;
    }`

**Comment by i-tudou** [comment]
@DeclanWang 我处理方法和你差不多。
```
private Map<String, Object> newKeyValues(List<Expression> expressions) {
        Map<String, Object> keyValues = new HashMap<>();
        for (int i = 0; i < columns.size(); i++) {
            columns.get(i).setTable(table);
            if (primaryKeys.contains(columns.get(i).getFullyQualifiedName())) {
                Object expression = null;
                if(ConverterUtil.isNotEmpty(expressions.get(i).getASTNode())){
                    expressions.get(i).getASTNode().jjtGetValue();
                }else{
                    expression = expressions.get(i);
                }
                keyValues.put(columns.get(i).getFullyQualifiedName(),
                        Reflection.invokeN(expression.getClass(), "getValue", expression, new Object[0]));
            }
        }
        return keyValues;
    }
```
