### ISSUE TITLE
com.codingapi.txlcn.common.exception.TxManagerException: attempts to join the non-existent transaction group

### ISSUE THREAD

**Issue by trisen** [codingapi/tx-lcn#323]
- [ ] I have searched the [issues](https://github.com/codingapi/tx-lcn/issues) of this repository and believe that this is not a duplicate.

### 1. Bug Description

正常请求后，两边的数据都入库了。 但是在服务方会报错
在发起方内部人为抛异常，服务方仍然入库了。

### 2. Environment:
- JDK version:
- OS:
- TX-LCN version:
- Others:

### 3. Exception Stacktrace
发起方代码：
```
   @Override
    @LcnTransaction(propagation = DTXPropagation.SUPPORTS)
    @Transactional
    public String excuteRPC(String exFlg) {

        Map map = new HashMap();
        map.put("fcode", "tx_aaa@163.com");
        map.put("fname", "tx_aaa1");
        map.put("fpassword", "123123");
//远端
        Object o = systemClient.createPerson(map);
//本地
        int i = txTestMapper.insert(TxTest.builder().name("zhangsan").build());
        if(!Objects.nonNull(exFlg)){
            throw new IllegalStateException();
        }
        return "ok";
}
```
服务方代码(远端)
```
 @Override
    @TxcTransaction(propagation = DTXPropagation.SUPPORTS)
    public boolean save(Person person) {
        person.setFstatus(StatusEnum.ENABLE.getCode());
        person.setFpassword(DigestUtils.md5DigestAsHex(person.getFpassword().getBytes()));
        return super.save(person);
    }
```

服务端异常：
```
2019-03-22 14:04:26.461 ERROR [provider-system-core,505c38b71ecf309c,f4b1f0d2cb4b66c9,false] 8772 --- [nio-9000-exec-1] c.c.txlcn.tc.core.DTXServiceExecutor     : 0ac2aa8daf800e16e93296eaa36e5326 @group(non)
2019-03-22 14:04:26.474 ERROR [provider-system-core,505c38b71ecf309c,f4b1f0d2cb4b66c9,false] 8772 --- [nio-9000-exec-1] c.c.f.hander.GlobalExceptionHandler      : 

java.lang.reflect.UndeclaredThrowableException: null
	at cn.com.finesoft.service.impl.PersonServiceImpl$$EnhancerBySpringCGLIB$$16fd8fc8.save(<generated>) ~[classes/:na]
	at cn.com.finesoft.controller.GenericController.save(GenericController.java:27) ~[classes/:na]
	at cn.com.finesoft.controller.PersonController.save(PersonController.java:49) ~[classes/:na]
	at cn.com.finesoft.controller.PersonController$$FastClassBySpringCGLIB$$f56d2569.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746) ~[spring-aop-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:52) ~[spring-aop-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:174) ~[spring-aop-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:52) ~[spring-aop-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:174) ~[spring-aop-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) ~[spring-aop-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) ~[spring-aop-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688) ~[spring-aop-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at cn.com.finesoft.controller.PersonController$$EnhancerBySpringCGLIB$$ca3c4c6e.save(<generated>) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_201]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209) ~[spring-web-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136) ~[spring-web-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102) ~[spring-webmvc-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:877) ~[spring-webmvc-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:783) ~[spring-webmvc-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991) ~[spring-webmvc-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925) ~[spring-webmvc-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974) [spring-webmvc-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:877) [spring-webmvc-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:851) [spring-webmvc-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-embed-websocket-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:158) [spring-boot-actuator-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:126) [spring-boot-actuator-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:111) [spring-boot-actuator-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:90) [spring-boot-actuator-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) [spring-web-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109) [spring-web-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93) [spring-web-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.springframework.cloud.sleuth.instrument.web.ExceptionLoggingFilter.doFilter(ExceptionLoggingFilter.java:48) [spring-cloud-sleuth-core-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at brave.servlet.TracingFilter.doFilter(TracingFilter.java:86) [brave-instrumentation-servlet-5.1.0.jar:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200) [spring-web-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1468) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_201]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_201]

```
管理端信息：

```
2019-03-22 14:04:26.403 ERROR 8948 --- [-rpc-service-12] c.c.t.t.t.t.JoinGroupExecuteService      : attempts to join the non-existent transaction group. [0ac2aa8daf800e16e93296eaa36e5326@provider-system-core] @group(non)
2019-03-22 14:04:26.404 ERROR 8948 --- [-rpc-service-12] c.c.txlcn.tm.txmsg.ServerRpcAnswer       : rpc execute service error. action: joinGroup

com.codingapi.txlcn.common.exception.TxManagerException: attempts to join the non-existent transaction group. [0ac2aa8daf800e16e93296eaa36e5326@provider-system-core]
	at com.codingapi.txlcn.tm.txmsg.transaction.JoinGroupExecuteService.execute(JoinGroupExecuteService.java:73) ~[txlcn-tm-5.0.2.RELEASE.jar:5.0.2.RELEASE]
	at com.codingapi.txlcn.tm.txmsg.ServerRpcAnswer.lambda$callback$0(ServerRpcAnswer.java:71) ~[txlcn-tm-5.0.2.RELEASE.jar:5.0.2.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_201]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_201]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_201]

2019-03-22 14:04:26.427  INFO 8948 --- [-rpc-service-13] c.c.t.t.s.s.impl.TxExceptionServiceImpl  : write tx_exception. WriteTxExceptionDTO(groupId=fcd56f50e537, unitId=0ac2aa8daf800e16e93296eaa36e5326, modId=provider-system-core, transactionState=0, registrar=4, remark=[StatementInfo(sql=DELETE  FROM tperson WHERE , params=[])])

```

**Comment by ujued** [comment]
发起方事务传播不能设置为 `DTXPropagation.SUPPORTS`

**Comment by trisen** [comment]
@ujued 去除DTXPropagation.SUPPORTS 正常情况不再报错。 但是在发起方主动发起错误。远端仍然会保存。事物并没有回滚。
管理端日志：2019-03-25 10:26:00.732  INFO 1796 --- [-rpc-service-10] c.c.t.t.s.s.impl.TxExceptionServiceImpl  : write tx_exception. WriteTxExceptionDTO(groupId=10b80406b12537, unitId=0ac2aa8daf800e16e93296eaa36e5326, modId=provider-system-core, transactionState=0, registrar=4, remark=[StatementInfo(sql=DELETE  FROM tperson WHERE , params=[])])

**Comment by trisen** [comment]
> 发起方事务传播不能设置为 `DTXPropagation.SUPPORTS`

去除DTXPropagation.SUPPORTS 正常情况不再报错。 但是在发起方主动发起错误。远端仍然会保存。事物并没有回滚。
管理端日志：2019-03-25 10:26:00.732 INFO 1796 --- [-rpc-service-10] c.c.t.t.s.s.impl.TxExceptionServiceImpl : write tx_exception. WriteTxExceptionDTO(groupId=10b80406b12537, unitId=0ac2aa8daf800e16e93296eaa36e5326, modId=provider-system-core, transactionState=0, registrar=4, remark=[StatementInfo(sql=DELETE FROM tperson WHERE , params=[])])

**Comment by ujued** [comment]
看到你参与方是TXC模式，你的Dao层需要配置可以获取自增主键，或参考https://www.txlcn.org/zh-cn/docs/setting/client.html，为服务增加业务主键

**Comment by trisen** [comment]
> 看到你参与方是TXC模式，你的Dao层需要配置可以获取自增主键，或参考[https://www.txlcn.org/zh-cn/docs/setting/client.html，为服务增加业务主键](https://www.txlcn.org/zh-cn/docs/setting/client.html%EF%BC%8C%E4%B8%BA%E6%9C%8D%E5%8A%A1%E5%A2%9E%E5%8A%A0%E4%B8%9A%E5%8A%A1%E4%B8%BB%E9%94%AE)

@Component
public class MysqlPrimaryKeysProvider implements PrimaryKeysProvider {
    @Override
    public Map<String, List<String>> provide() {
        return Maps.newHashMap("tperson", Collections.singletonList("fid"));
    }
}

远程端配置了，仍然没有删除相应记录呀。

管理端日志还是这样：
remark=[StatementInfo(sql=DELETE  FROM tperson WHERE , params=[])])

**Comment by trisen** [comment]
> 看到你参与方是TXC模式，你的Dao层需要配置可以获取自增主键，或参考[https://www.txlcn.org/zh-cn/docs/setting/client.html，为服务增加业务主键](https://www.txlcn.org/zh-cn/docs/setting/client.html%EF%BC%8C%E4%B8%BA%E6%9C%8D%E5%8A%A1%E5%A2%9E%E5%8A%A0%E4%B8%9A%E5%8A%A1%E4%B8%BB%E9%94%AE)

我把远程的改成@LcnTransaction 同样效果。

**Comment by realjerrytang** [comment]
问题又解决吗，我这边也遇到一样的问题~~

**Comment by realjerrytang** [comment]
tx-manager链接mycat数据库，报java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'order LIKE '%'' at l，直接连接数据不会报错
