### ISSUE TITLE
出现以下错误，然后一直重启

### ISSUE THREAD

**Issue by xqq1994** [codingapi/tx-lcn#328]
Exception in thread "Thread-16" java.lang.IllegalStateException: There is no normal TM.
at com.codingapi.txlcn.tc.txmsg.TMSearcher.search(TMSearcher.java:86)
at com.codingapi.txlcn.tc.txmsg.AutoTMClusterEngine.prepareToResearchTMCluster(AutoTMClusterEngine.java:83)
at com.codingapi.txlcn.tc.txmsg.AutoTMClusterEngine.onInitialized(AutoTMClusterEngine.java:57)
at com.codingapi.txlcn.tc.txmsg.TCSideRpcInitCallBack.lambda$null$1(TCSideRpcInitCallBack.java:95)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at com.codingapi.txlcn.tc.txmsg.TCSideRpcInitCallBack.lambda$connected$2(TCSideRpcInitCallBack.java:95)
at java.lang.Thread.run(Thread.java:745)

**Comment by xqq1994** [comment]
Send init message exception: request timeout.. connect fail!

**Comment by xqq1994** [comment]
Exception in thread "Thread-17" java.lang.IllegalArgumentException: count < 0
at java.util.concurrent.CountDownLatch.<init>(CountDownLatch.java:199)
at com.codingapi.txlcn.tc.txmsg.TMSearcher.search(TMSearcher.java:80)
at com.codingapi.txlcn.tc.txmsg.AutoTMClusterEngine.prepareToResearchTMCluster(AutoTMClusterEngine.java:83)
at com.codingapi.txlcn.tc.txmsg.AutoTMClusterEngine.onInitialized(AutoTMClusterEngine.java:57)
at com.codingapi.txlcn.tc.txmsg.TCSideRpcInitCallBack.lambda$null$1(TCSideRpcInitCallBack.java:95)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at com.codingapi.txlcn.tc.txmsg.TCSideRpcInitCallBack.lambda$connected$2(TCSideRpcInitCallBack.java:95)
at java.lang.Thread.run(Thread.java:745)

**Comment by xqq1994** [comment]
请官方解答

**Comment by yizhishang** [comment]
tm地址没有配置吧

**Comment by brake-lin** [comment]
1.tm地址没有配置

**Comment by brake-lin** [comment]
2.tm没有启动
