### ISSUE TITLE
java.lang.Exception: tx-manager not connected ,please check tx-manager server 

### ISSUE THREAD

**Issue by wuyhVputin** [codingapi/tx-lcn#354]
有没有人在跑springcloud-lcn-demo 的时候发现a服务DemoController调用save方法的时候报错:
错误日志如下
2019-04-18 19:27:32.578 ERROR 5756 --- [nio-9002-exec-4] c.c.t.n.service.impl.NettyServiceImpl    : socket not connection wait 2 seconds.
2019-04-18 19:27:34.579 ERROR 5756 --- [nio-9002-exec-4] c.c.t.n.service.impl.NettyServiceImpl    : socket not connection,check txManager server .
2019-04-18 19:27:34.588 ERROR 5756 --- [nio-9002-exec-4] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.reflect.UndeclaredThrowableException] with root cause

java.lang.Exception: tx-manager not connected ,please check tx-manager server 
	at com.codingapi.tx.aop.service.impl.TransactionServerFactoryServiceImpl.createTransactionServer(TransactionServerFactoryServiceImpl.java:52) ~[tx-client-4.1.0.jar:na]
	at com.codingapi.tx.aop.service.impl.AspectBeforeServiceImpl.around(AspectBeforeServiceImpl.java:50) ~[tx-client-4.1.0.jar:na]
	at com.codingapi.tx.springcloud.interceptor.TxManagerInterceptor.around(TxManagerInterceptor.java:30) ~[transaction-springcloud-4.1.0.jar:na]
	at com.codingapi.tx.springcloud.interceptor.TransactionAspect.transactionRunning(TransactionAspect.java:30) ~[transaction-springcloud-4.1.0.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_201]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:629) ~[spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:618) ~[spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70) ~[spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168) ~[spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:656) ~[spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at cn.ehanghai.cloud.service.member.service.ShareResultsService$$EnhancerBySpringCGLIB$$9d257d45.getMoneyByRedEnvelope(<generated>) ~[classes/:na]

**Comment by Zhouyongnan** [comment]
我也遇到这个问题 整合失败

**Comment by cdw1200** [comment]
我也遇到这个问题 整合失败我也遇到这个问题 整合失败

**Comment by ffxxbb** [comment]
怎么解决的

**Comment by h510695134** [comment]
> 我也遇到这个问题 整合失败我也遇到这个问题 整合失败

请问怎么解决的呢
