### ISSUE TITLE
项目启动报错redis在哪配置的？tm无法启动成redis127.0.0.1:6379

### ISSUE THREAD

**Issue by luyiceo** [codingapi/tx-lcn#355]
## Why you need it?
 Is your feature request related to a problem? Please describe in details

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by luyiceo** [comment]
java.lang.IllegalStateException: Failed to execute ApplicationRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:807) [spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:794) [spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:324) [spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) [spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) [spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.txlcn.tm.TransactionManagerApplication.main(TransactionManagerApplication.java:12) [classes/:na]
Caused by: org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to localhost:6379

**Comment by luyiceo** [comment]
... 5 common frames omitted
Caused by: io.lettuce.core.RedisConnectionException: Unable to connect to localhost:6379
	at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:78) ~[lettuce-core-5.1.3.RELEASE.jar:na]
	at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:56) ~[lettuce-core-5.1.3.RELEASE.jar:na]
	at io.lettuce.core.AbstractRedisClient.getConnection(AbstractRedisClient.java:234) ~[lettuce-core-5.1.3.RELEASE.jar:na]
	at io.lettuce.core.RedisClient.connect(RedisClient.java:204) ~[lettuce-core-5.1.3.RELEASE.jar:na]
	at org.springframework.data.redis.connection.lettuce.StandaloneConnectionProvider.lambda$getConnection$1(StandaloneConnectionProvider.java:113) ~[spring-data-redis-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at java.util.Optional.orElseGet(Optional.java:267) ~[na:1.8.0_144]
	at org.springframework.data.redis.connection.lettuce.StandaloneConnectionProvider.getConnection(StandaloneConnectionProvider.java:113) ~[spring-data-redis-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$SharedConnection.getNativeConnection(LettuceConnectionFactory.java:1085) ~[spring-data-redis-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	... 21 common frames omitted
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_144]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[na:1.8.0_144]
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327) ~[netty-all-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340) ~[netty-all-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:636) ~[netty-all-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583) ~[netty-all-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500) ~[netty-all-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462) ~[netty-all-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897) ~[netty-all-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-all-4.1.31.Final.jar:4.1.31.Final]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_144]
Caused by: java.net.ConnectException: Connection refused: no further information

**Comment by luyiceo** [comment]
2019-04-21 08:52:37.838  INFO 28224 --- [           main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 3016 ms
Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
2019-04-21 08:52:38.980  INFO 28224 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2019-04-21 08:52:38.982  WARN 28224 --- [           main] com.zaxxer.hikari.util.DriverDataSource  : Registered driver with driverClassName=com.mysql.jdbc.Driver was not found, trying direct instantiation.
2019-04-21 08:52:39.161  INFO 28224 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2019-04-21 08:52:39.229  INFO 28224 --- [           main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [
	name: default
	...]
2019-04-21 08:52:39.365  INFO 28224 --- [           main] org.hibernate.Version                    : HHH000412: Hibernate Core {5.3.7.Final}
2019-04-21 08:52:39.369  INFO 28224 --- [           main] org.hibernate.cfg.Environment            : HHH000206: hibernate.properties not found
2019-04-21 08:52:39.696  INFO 28224 --- [           main] o.hibernate.annotations.common.Version   : HCANN000001: Hibernate Commons Annotations {5.0.4.Final}
2019-04-21 08:52:39.963  INFO 28224 --- [           main] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: org.hibernate.dialect.MySQL5InnoDBDialect
2019-04-21 08:52:40.988  INFO 28224 --- [           main] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
2019-04-21 08:52:42.126  WARN 28224 --- [           main] aWebConfiguration$JpaWebMvcConfiguration : spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
2019-04-21 08:52:42.873  INFO 28224 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 2 endpoint(s) beneath base path '/actuator'
2019-04-21 08:52:43.010  INFO 28224 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 7970 (http) with context path ''
2019-04-21 08:52:43.013  INFO 28224 --- [           main] o.t.tm.TransactionManagerApplication     : Started TransactionManagerApplication in 8.814 seconds (JVM running for 12.507)
2019-04-21 08:52:45.452  INFO 28224 --- [           main] c.c.t.t.n.i.NettyRpcServerInitializer    : Socket started on 127.0.0.1:8070 
2019-04-21 08:52:45.468  INFO 28224 --- [ntLoopGroup-4-1] io.netty.handler.logging.LoggingHandler  : [id: 0xdad1107d] REGISTERED
2019-04-21 08:52:45.470  INFO 28224 --- [ntLoopGroup-4-1] io.netty.handler.logging.LoggingHandler  : [id: 0xdad1107d] BIND: /127.0.0.1:8070
2019-04-21 08:52:45.474  INFO 28224 --- [ntLoopGroup-4-1] io.netty.handler.logging.LoggingHandler  : [id: 0xdad1107d, L:/127.0.0.1:8070] ACTIVE
2019-04-21 08:52:45.584  INFO 28224 --- [           main] io.lettuce.core.EpollProvider            : Starting without optional epoll library
2019-04-21 08:52:45.587  INFO 28224 --- [           main] io.lettuce.core.KqueueProvider           : Starting without optional kqueue library
2019-04-21 08:52:47.752  INFO 28224 --- [           main] ConditionEvaluationReportLoggingListener :

**Comment by luyiceo** [comment]
java.lang.IllegalStateException: Failed to execute ApplicationRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:807) [spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:794) [spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:324) [spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) [spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) [spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.txlcn.tm.TransactionManagerApplication.main(TransactionManagerApplication.java:12) [classes/:na]
Caused by: org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to localhost:6379
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$SharedConnection.getNativeConnection(LettuceConnectionFactory.java:1092) ~[spring-data-redis-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$SharedConnection.getConnection(LettuceConnectionFactory.java:1065) ~[spring-data-redis-2.1.4.RELEASE.jar:2.1.4.RELEASE]

**Comment by luyiceo** [comment]
2019-04-21 08:52:48.815  INFO 28224 --- [           main] o.s.b.f.support.DisposableBeanAdapter    : Invocation of destroy method failed on bean with name 'txLcnApplicationRunner': org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to localhost:6379
2019-04-21 08:52:48.816  INFO 28224 --- [           main] o.s.b.f.support.DisposableBeanAdapter    : Invocation of destroy method failed on bean with name 'nettyRpcClientInitializer': java.lang.NullPointerException
2019-04-21 08:52:48.846  INFO 28224 --- [ntLoopGroup-4-1] io.netty.handler.logging.LoggingHandler  : [id: 0xdad1107d, L:/127.0.0.1:8070] UNREGISTERED
2019-04-21 08:52:48.863  INFO 28224 --- [           main] c.c.t.t.n.i.NettyRpcServerInitializer    : server was down.
2019-04-21 08:52:48.865  INFO 28224 --- [           main] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2019-04-21 08:52:50.000  INFO 28224 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2019-04-21 08:52:50.015  INFO 28224 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
Disconnected from the target VM, address: '127.0.0.1:54006', transport: 'socket'
