### ISSUE TITLE
使用LCN5.0.2,使用eureka注册中心报错

### ISSUE THREAD

**Issue by oulexue** [codingapi/tx-lcn#392]
- [ ] I have searched the [issues](https://github.com/codingapi/tx-lcn/issues) of this repository and believe that this is not a duplicate.

### 1. Bug Description
springboot1.5.19版，springcloud Dalston.SR1版 使用eureka1.3.1做为注册中心，访问请求时报错

### 2. Environment:
- JDK version:
- OS:
- TX-LCN version: 5.0.2
- Others:
springboot1.5.19版，springcloud Dalston.SR1版
### 3. Exception Stacktrace
java.lang.AbstractMethodError: org.springframework.cloud.netflix.eureka.serviceregistry.EurekaRegistration.getHost()Ljava/lang/String;
at com.codingapi.txlcn.tracing.http.ribbon.TxlcnZoneAvoidanceRule.choose(TxlcnZoneAvoidanceRule.java:60) ~[txlcn-tracing-5.0.2.RELEASE.jar:5.0.2.RELEASE]
	at com.netflix.loadbalancer.BaseLoadBalancer.chooseServer(BaseLoadBalancer.java:736) ~[ribbon-loadbalancer-2.2.2.jar:2.2.2]
	at com.netflix.loadbalancer.ZoneAwareLoadBalancer.chooseServer(ZoneAwareLoadBalancer.java:113) ~[ribbon-loadbalancer-2.2.2.jar:2.2.2]

### 4. Tour Idea
eureka版本号1.3.1太低，EurekaRegistration没有提供getHost等方法

**Comment by iamdiffuser** [comment]
1.5.是我这里是有问题，spring boot 升级为2.1.2.RELEASE

**Comment by oulexue** [comment]
多谢，目前已解决，springboot版本未变，springcloud版本改为了Edgware版，运行正常。另外还有两个问题您确认:1.使用TxcTransaction模式，针对负责sql不支持，改为LCN模式正常。2.使用LCN模式事务结束后，导致线程池关闭，后面继续使用事务保存connection holder is null 。3.tc集群不改变标识策略会出问题吗？目前我这边按官网改成了机器名+端口号



发自我的小米手机在 iamdiffuser <notifications@github.com>，2019年7月9日 上午9:14写道：1.5.是我这里是有问题，spring boot 升级为2.1.2.RELEASE



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/codingapi/tx-lcn/issues/392?email_source=notifications\u0026email_token=AGLNULOJTBAAWC6D54PZPIDP6PQ77A5CNFSM4H4ME2N2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZOZBZY#issuecomment-509448423",

"url": "https://github.com/codingapi/tx-lcn/issues/392?email_source=notifications\u0026email_token=AGLNULOJTBAAWC6D54PZPIDP6PQ77A5CNFSM4H4ME2N2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZOZBZY#issuecomment-509448423",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
