### ISSUE TITLE
【服务注册不正常】redis 开启哨兵模式（1主2从），tx-manager采用双节点

### ISSUE THREAD

**Issue by HongKing** [codingapi/tx-lcn#412]
I have searched the [issues](https://github.com/codingapi/tx-lcn/issues) of this repository and believe that this is not a duplicate.

### 1. Bug Description
redis 开启哨兵模式（1主2从），tx-manager采用双节点，长时间运行后，当有新的服务启动时报错，不能注册到tx-maner上，重启tx-manger后可正常，但分别将tx-manger的双节点启动后，前端提示有3个tx-manger节点,

### 2. Environment:
- JDK version:1.8
- OS:win 10
- TX-LCN version:5.0.2
- Others: redis 5

### 3. Exception Stacktrace
重启tx-manager前的错误日志

 ```
[2019-07-23 10:47:10.903] [restartedMain] [INFO ] com.codingapi.txlcn.tc.corelog.aspect.AspectLogHelper [62] - Aspect log table finished (H2 DATABASE)
[2019-07-23 10:47:11.057] [restartedMain] [INFO ] com.codingapi.txlcn.txmsg.netty.impl.NettyRpcClientInitializer [102] - Try connect socket(/112.128.4.22:9700) - count 1
[2019-07-23 10:47:11.635] [restartedMain] [INFO ] com.codingapi.txlcn.txmsg.netty.impl.NettyRpcClientInitializer [102] - Try connect socket(/112.128.4.23:9700) - count 1
[2019-07-23 10:47:11.636] [Thread-18] [INFO ] com.codingapi.txlcn.tc.txmsg.TCSideRpcInitCallBack [77] - Send init message to TM[/112.128.4.22:9700]
[2019-07-23 10:47:11.738] [Thread-19] [INFO ] com.codingapi.txlcn.tc.txmsg.TCSideRpcInitCallBack [77] - Send init message to TM[/112.128.4.23:9700]
[2019-07-23 10:47:11.741] [restartedMain] [INFO ] com.codingapi.txlcn.tc.corelog.txc.TxcLogHelper [59] - Txc log table finish (H2 DATABASE)
[2019-07-23 10:47:11.848] [Thread-18] [DEBUG] com.codingapi.txlcn.txmsg.netty.bean.SocketManager [123] - get channel, key:/112.128.4.22:9700
[2019-07-23 10:47:12.039] [Thread-19] [DEBUG] com.codingapi.txlcn.txmsg.netty.bean.SocketManager [123] - get channel, key:/112.128.4.23:9700
[2019-07-23 10:47:12.162] [Thread-18] [DEBUG] com.codingapi.txlcn.txmsg.netty.bean.SocketManager [126] - await response
[2019-07-23 10:47:12.170] [nioEventLoopGroup-4-1] [DEBUG] com.codingapi.txlcn.txmsg.netty.handler.RpcCmdEncoder [40] - send->{"key":"3758ece262537","msg":{"action":"init","data":{"appName":"service-data","dtxTime":0,"labelName":"112.128.4.100:7005","machineId":0,"seqLen":0,"tmRpcTimeout":0},"state":100},"remoteKey":"/112.128.4.22:9700"}
[2019-07-23 10:47:12.239] [Thread-19] [DEBUG] com.codingapi.txlcn.txmsg.netty.bean.SocketManager [126] - await response
[2019-07-23 10:47:12.239] [nioEventLoopGroup-4-2] [DEBUG] com.codingapi.txlcn.txmsg.netty.handler.RpcCmdEncoder [40] - send->{"key":"3758ecee22537","msg":{"action":"init","data":{"appName":"service-data","dtxTime":0,"labelName":"112.128.4.100:7005","machineId":0,"seqLen":0,"tmRpcTimeout":0},"state":100},"remoteKey":"/112.128.4.23:9700"}
[2019-07-23 10:47:12.895] [nioEventLoopGroup-4-2] [DEBUG] com.codingapi.txlcn.txmsg.netty.handler.RpcCmdDecoder [51] - cmd->{"key":"3758ecee22537","msg":{"action":"init","data":{"appName":"tx-manager:8790","dtxTime":36000,"labelName":"112.128.4.100:7005","machineId":955,"seqLen":12,"tmRpcTimeout":1000},"state":200},"remoteKey":"/112.128.4.100:51082"}
[2019-07-23 10:47:12.895] [nioEventLoopGroup-4-1] [DEBUG] com.codingapi.txlcn.txmsg.netty.handler.RpcCmdDecoder [51] - cmd->{"key":"3758ece262537","msg":{"action":"init","data":{"appName":"tx-manager:8790","dtxTime":36000,"labelName":"112.128.4.100:7005","machineId":954,"seqLen":12,"tmRpcTimeout":1000},"state":200},"remoteKey":"/112.128.4.100:51081"}
[2019-07-23 10:47:12.997] [nioEventLoopGroup-4-2] [DEBUG] com.codingapi.txlcn.txmsg.netty.handler.RpcCmdDecoder [70] - got response message[Netty Handler]
[2019-07-23 10:47:13.098] [nioEventLoopGroup-4-1] [DEBUG] com.codingapi.txlcn.txmsg.netty.handler.RpcCmdDecoder [70] - got response message[Netty Handler]
[2019-07-23 10:47:13.198] [Thread-19] [DEBUG] com.codingapi.txlcn.txmsg.netty.bean.NettyRpcCmd [54] - got response. 3758ecee22537 
[2019-07-23 10:47:13.299] [Thread-18] [DEBUG] com.codingapi.txlcn.txmsg.netty.bean.NettyRpcCmd [54] - got response. 3758ece262537 
[2019-07-23 10:47:13.400] [Thread-19] [DEBUG] com.codingapi.txlcn.txmsg.netty.bean.SocketManager [133] - response is: MessageDto(action=init, groupId=null, data=InitClientParams(appName=tx-manager:8790, labelName=112.128.4.100:7005, dtxTime=36000, tmRpcTimeout=1000, seqLen=12, machineId=955), state=200)
[2019-07-23 10:47:13.501] [Thread-18] [DEBUG] com.codingapi.txlcn.txmsg.netty.bean.SocketManager [133] - response is: MessageDto(action=init, groupId=null, data=InitClientParams(appName=tx-manager:8790, labelName=112.128.4.100:7005, dtxTime=36000, tmRpcTimeout=1000, seqLen=12, machineId=954), state=200)
[2019-07-23 10:47:13.601] [Thread-19] [DEBUG] com.codingapi.txlcn.txmsg.netty.impl.NettyRpcClient [83] - cmd request used time: 1563 ms
[2019-07-23 10:47:13.702] [Thread-18] [DEBUG] com.codingapi.txlcn.txmsg.netty.impl.NettyRpcClient [83] - cmd request used time: 1861 ms
[2019-07-23 10:47:13.804] [Thread-19] [INFO ] com.codingapi.txlcn.tc.txmsg.TCSideRpcInitCallBack [92] - Finally, determined dtx time is 36000ms, tm rpc timeout is 1000 ms, machineId is 955
[2019-07-23 10:47:13.904] [Thread-18] [INFO ] com.codingapi.txlcn.tc.txmsg.TCSideRpcInitCallBack [92] - Finally, determined dtx time is 36000ms, tm rpc timeout is 1000 ms, machineId is 954
[2019-07-23 10:47:14.004] [Thread-19] [INFO ] com.codingapi.txlcn.tc.txmsg.TMSearcher [111] - TM cluster's size: 2
[2019-07-23 10:47:14.105] [Thread-18] [INFO ] com.codingapi.txlcn.tc.txmsg.TMSearcher [72] - Searching for more TM...
[2019-07-23 10:47:14.306] [Thread-18] [DEBUG] com.codingapi.txlcn.txmsg.netty.bean.SocketManager [123] - get channel, key:/112.128.4.22:9700
[2019-07-23 10:47:14.408] [Thread-18] [DEBUG] com.codingapi.txlcn.txmsg.netty.bean.SocketManager [126] - await response
[2019-07-23 10:47:14.408] [nioEventLoopGroup-4-1] [DEBUG] com.codingapi.txlcn.txmsg.netty.handler.RpcCmdEncoder [40] - send->{"key":"3758ed1873b8537","msg":{"action":"qtmc","state":100},"remoteKey":"/112.128.4.22:9700"}
[2019-07-23 10:47:14.747] [nioEventLoopGroup-4-1] [DEBUG] com.codingapi.txlcn.txmsg.netty.handler.RpcCmdDecoder [51] - cmd->{"key":"3758ed1873b8537","msg":{"action":"qtmc","data":["112.128.4.22:9700"],"state":200},"remoteKey":"/112.128.4.100:51081"}
[2019-07-23 10:47:14.849] [nioEventLoopGroup-4-1] [DEBUG] com.codingapi.txlcn.txmsg.netty.handler.RpcCmdDecoder [70] - got response message[Netty Handler]
[2019-07-23 10:47:14.950] [Thread-18] [DEBUG] com.codingapi.txlcn.txmsg.netty.bean.NettyRpcCmd [54] - got response. 3758ed1873b8537 
[2019-07-23 10:47:15.050] [Thread-18] [DEBUG] com.codingapi.txlcn.txmsg.netty.bean.SocketManager [133] - response is: MessageDto(action=qtmc, groupId=null, data=[112.128.4.22:9700], state=200)
[2019-07-23 10:47:15.151] [Thread-18] [DEBUG] com.codingapi.txlcn.txmsg.netty.impl.NettyRpcClient [83] - cmd request used time: 845 ms
[2019-07-23 10:47:15.252] [Thread-18] [DEBUG] com.codingapi.txlcn.tc.txmsg.LoopMessenger [164] - request action: qtmc. TM[/112.128.4.22:9700]
Exception in thread "Thread-18" java.lang.IllegalArgumentException: count < 0
	at java.util.concurrent.CountDownLatch.<init>(CountDownLatch.java:199)
	at com.codingapi.txlcn.tc.txmsg.TMSearcher.search(TMSearcher.java:80)
	at com.codingapi.txlcn.tc.txmsg.AutoTMClusterEngine.prepareToResearchTMCluster(AutoTMClusterEngine.java:83)
	at com.codingapi.txlcn.tc.txmsg.AutoTMClusterEngine.onInitialized(AutoTMClusterEngine.java:57)
	at com.codingapi.txlcn.tc.txmsg.TCSideRpcInitCallBack.lambda$null$1(TCSideRpcInitCallBack.java:95)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.codingapi.txlcn.tc.txmsg.TCSideRpcInitCallBack.lambda$connected$2(TCSideRpcInitCallBack.java:95)
	at java.lang.Thread.run(Thread.java:748)
```
将两个tx-manager分别重启后（每次都至少有一个在运行），可以看到最后一行的日志（TM cluster's size: 3）
```
[2019-07-23 10:50:33.649] [nioEventLoopGroup-4-2] [ERROR] com.codingapi.txlcn.txmsg.netty.handler.NettyClientRetryHandler [75] - keepSize:2,nowSize:1
[2019-07-23 10:50:33.751] [nioEventLoopGroup-4-2] [ERROR] com.codingapi.txlcn.txmsg.netty.handler.NettyClientRetryHandler [78] - socketAddress:/112.128.4.23:9700 
[2019-07-23 10:50:33.854] [nioEventLoopGroup-4-2] [INFO ] com.codingapi.txlcn.txmsg.netty.impl.NettyRpcClientInitializer [102] - Try connect socket(/112.128.4.23:9700) - count 1
[2019-07-23 10:50:34.960] [nioEventLoopGroup-4-2] [WARN ] com.codingapi.txlcn.txmsg.netty.impl.NettyRpcClientInitializer [111] - Connect socket(/112.128.4.23:9700) fail. 6000ms latter try again.
[2019-07-23 10:50:41.064] [nioEventLoopGroup-4-2] [INFO ] com.codingapi.txlcn.txmsg.netty.impl.NettyRpcClientInitializer [102] - Try connect socket(/112.128.4.23:9700) - count 2
[2019-07-23 10:50:42.170] [nioEventLoopGroup-4-2] [WARN ] com.codingapi.txlcn.txmsg.netty.impl.NettyRpcClientInitializer [111] - Connect socket(/112.128.4.23:9700) fail. 6000ms latter try again.
[2019-07-23 10:50:45.831] [nioEventLoopGroup-4-1] [ERROR] com.codingapi.txlcn.txmsg.netty.handler.NettyClientRetryHandler [75] - keepSize:2,nowSize:0
[2019-07-23 10:50:45.934] [nioEventLoopGroup-4-1] [ERROR] com.codingapi.txlcn.txmsg.netty.handler.NettyClientRetryHandler [78] - socketAddress:/112.128.4.22:9700 
[2019-07-23 10:50:48.272] [nioEventLoopGroup-4-2] [INFO ] com.codingapi.txlcn.txmsg.netty.impl.NettyRpcClientInitializer [102] - Try connect socket(/112.128.4.23:9700) - count 3
[2019-07-23 10:50:49.376] [nioEventLoopGroup-4-2] [WARN ] com.codingapi.txlcn.txmsg.netty.impl.NettyRpcClientInitializer [111] - Connect socket(/112.128.4.23:9700) fail. 6000ms latter try again.
[2019-07-23 10:50:55.479] [nioEventLoopGroup-4-2] [INFO ] com.codingapi.txlcn.txmsg.netty.impl.NettyRpcClientInitializer [102] - Try connect socket(/112.128.4.23:9700) - count 4
[2019-07-23 10:50:56.584] [nioEventLoopGroup-4-2] [WARN ] com.codingapi.txlcn.txmsg.netty.impl.NettyRpcClientInitializer [111] - Connect socket(/112.128.4.23:9700) fail. 6000ms latter try again.
[2019-07-23 10:51:02.688] [nioEventLoopGroup-4-2] [INFO ] com.codingapi.txlcn.txmsg.netty.impl.NettyRpcClientInitializer [102] - Try connect socket(/112.128.4.23:9700) - count 5
[2019-07-23 10:51:02.790] [nioEventLoopGroup-4-1] [INFO ] com.codingapi.txlcn.txmsg.netty.impl.NettyRpcClientInitializer [102] - Try connect socket(/112.128.4.22:9700) - count 1
[2019-07-23 10:51:02.791] [Thread-20] [INFO ] com.codingapi.txlcn.tc.txmsg.TCSideRpcInitCallBack [77] - Send init message to TM[/112.128.4.23:9700]
[2019-07-23 10:51:02.993] [Thread-20] [DEBUG] com.codingapi.txlcn.txmsg.netty.bean.SocketManager [123] - get channel, key:/112.128.4.23:9700
[2019-07-23 10:51:03.094] [Thread-20] [DEBUG] com.codingapi.txlcn.txmsg.netty.bean.SocketManager [126] - await response
[2019-07-23 10:51:03.094] [nioEventLoopGroup-4-7] [DEBUG] com.codingapi.txlcn.txmsg.netty.handler.RpcCmdEncoder [40] - send->{"key":"3759254c83b8537","msg":{"action":"init","data":{"appName":"service-data","dtxTime":0,"labelName":"112.128.4.100:7005","machineId":0,"seqLen":0,"tmRpcTimeout":0},"state":100},"remoteKey":"/112.128.4.23:9700"}
[2019-07-23 10:51:03.307] [nioEventLoopGroup-4-7] [DEBUG] com.codingapi.txlcn.txmsg.netty.handler.RpcCmdDecoder [51] - cmd->{"key":"3759254c83b8537","msg":{"action":"init","data":{"appName":"tx-manager:8790","dtxTime":36000,"labelName":"112.128.4.100:7005","machineId":961,"seqLen":12,"tmRpcTimeout":1000},"state":200},"remoteKey":"/112.128.4.100:51149"}
[2019-07-23 10:51:03.409] [nioEventLoopGroup-4-7] [DEBUG] com.codingapi.txlcn.txmsg.netty.handler.RpcCmdDecoder [70] - got response message[Netty Handler]
[2019-07-23 10:51:03.510] [Thread-20] [DEBUG] com.codingapi.txlcn.txmsg.netty.bean.NettyRpcCmd [54] - got response. 3759254c83b8537 
[2019-07-23 10:51:03.610] [Thread-20] [DEBUG] com.codingapi.txlcn.txmsg.netty.bean.SocketManager [133] - response is: MessageDto(action=init, groupId=null, data=InitClientParams(appName=tx-manager:8790, labelName=112.128.4.100:7005, dtxTime=36000, tmRpcTimeout=1000, seqLen=12, machineId=961), state=200)
[2019-07-23 10:51:03.711] [Thread-20] [DEBUG] com.codingapi.txlcn.txmsg.netty.impl.NettyRpcClient [83] - cmd request used time: 718 ms
[2019-07-23 10:51:03.812] [Thread-20] [INFO ] com.codingapi.txlcn.tc.txmsg.TCSideRpcInitCallBack [92] - Finally, determined dtx time is 36000ms, tm rpc timeout is 1000 ms, machineId is 961
[2019-07-23 10:51:03.902] [nioEventLoopGroup-4-1] [WARN ] com.codingapi.txlcn.txmsg.netty.impl.NettyRpcClientInitializer [111] - Connect socket(/112.128.4.22:9700) fail. 6000ms latter try again.
[2019-07-23 10:51:03.912] [Thread-20] [INFO ] com.codingapi.txlcn.tc.txmsg.TMSearcher [111] - TM cluster's size: 1
[2019-07-23 10:51:10.013] [nioEventLoopGroup-4-1] [INFO ] com.codingapi.txlcn.txmsg.netty.impl.NettyRpcClientInitializer [102] - Try connect socket(/112.128.4.22:9700) - count 2
[2019-07-23 10:51:10.114] [nioEventLoopGroup-4-1] [WARN ] com.codingapi.txlcn.txmsg.netty.impl.NettyRpcClientInitializer [111] - Connect socket(/112.128.4.22:9700) fail. 6000ms latter try again.
[2019-07-23 10:51:16.216] [nioEventLoopGroup-4-1] [INFO ] com.codingapi.txlcn.txmsg.netty.impl.NettyRpcClientInitializer [102] - Try connect socket(/112.128.4.22:9700) - count 3
[2019-07-23 10:51:17.321] [nioEventLoopGroup-4-1] [WARN ] com.codingapi.txlcn.txmsg.netty.impl.NettyRpcClientInitializer [111] - Connect socket(/112.128.4.22:9700) fail. 6000ms latter try again.
[2019-07-23 10:51:23.422] [nioEventLoopGroup-4-1] [INFO ] com.codingapi.txlcn.txmsg.netty.impl.NettyRpcClientInitializer [102] - Try connect socket(/112.128.4.22:9700) - count 4
[2019-07-23 10:51:24.525] [nioEventLoopGroup-4-1] [WARN ] com.codingapi.txlcn.txmsg.netty.impl.NettyRpcClientInitializer [111] - Connect socket(/112.128.4.22:9700) fail. 6000ms latter try again.
[2019-07-23 10:51:30.628] [nioEventLoopGroup-4-1] [INFO ] com.codingapi.txlcn.txmsg.netty.impl.NettyRpcClientInitializer [102] - Try connect socket(/112.128.4.22:9700) - count 5
[2019-07-23 10:51:31.231] [Thread-21] [INFO ] com.codingapi.txlcn.tc.txmsg.TCSideRpcInitCallBack [77] - Send init message to TM[/112.128.4.22:9700]
[2019-07-23 10:51:31.232] [Thread-22] [INFO ] com.codingapi.txlcn.tc.txmsg.TCSideRpcInitCallBack [77] - Send init message to TM[/112.128.4.22:9700]
[2019-07-23 10:51:31.332] [Thread-21] [DEBUG] com.codingapi.txlcn.txmsg.netty.bean.SocketManager [123] - get channel, key:/112.128.4.22:9700
[2019-07-23 10:51:31.433] [Thread-22] [DEBUG] com.codingapi.txlcn.txmsg.netty.bean.SocketManager [123] - get channel, key:/112.128.4.22:9700
[2019-07-23 10:51:31.533] [Thread-21] [DEBUG] com.codingapi.txlcn.txmsg.netty.bean.SocketManager [126] - await response
[2019-07-23 10:51:31.533] [nioEventLoopGroup-4-4] [DEBUG] com.codingapi.txlcn.txmsg.netty.handler.RpcCmdEncoder [40] - send->{"key":"37592c5853c3537","msg":{"action":"init","data":{"appName":"service-data","dtxTime":0,"labelName":"112.128.4.100:7005","machineId":0,"seqLen":0,"tmRpcTimeout":0},"state":100},"remoteKey":"/112.128.4.22:9700"}
[2019-07-23 10:51:31.634] [Thread-22] [DEBUG] com.codingapi.txlcn.txmsg.netty.bean.SocketManager [126] - await response
[2019-07-23 10:51:31.736] [nioEventLoopGroup-4-4] [DEBUG] com.codingapi.txlcn.txmsg.netty.handler.RpcCmdEncoder [40] - send->{"key":"37592c4203c3537","msg":{"action":"init","data":{"appName":"service-data","dtxTime":0,"labelName":"112.128.4.100:7005","machineId":0,"seqLen":0,"tmRpcTimeout":0},"state":100},"remoteKey":"/112.128.4.22:9700"}
[2019-07-23 10:51:32.225] [nioEventLoopGroup-4-4] [DEBUG] com.codingapi.txlcn.txmsg.netty.handler.RpcCmdDecoder [51] - cmd->{"key":"37592c4203c3537","msg":{"action":"init","data":{"appName":"tx-manager:8790","dtxTime":36000,"labelName":"112.128.4.100:7005","machineId":967,"seqLen":12,"tmRpcTimeout":1000},"state":200},"remoteKey":"/112.128.4.100:51161"}
[2019-07-23 10:51:32.326] [nioEventLoopGroup-4-4] [DEBUG] com.codingapi.txlcn.txmsg.netty.handler.RpcCmdDecoder [70] - got response message[Netty Handler]
[2019-07-23 10:51:32.427] [Thread-22] [DEBUG] com.codingapi.txlcn.txmsg.netty.bean.NettyRpcCmd [54] - got response. 37592c4203c3537 
[2019-07-23 10:51:32.428] [nioEventLoopGroup-4-4] [DEBUG] com.codingapi.txlcn.txmsg.netty.handler.RpcCmdDecoder [51] - cmd->{"key":"37592c5853c3537","msg":{"action":"init","data":{"appName":"tx-manager:8790","dtxTime":36000,"labelName":"112.128.4.100:7005","machineId":970,"seqLen":12,"tmRpcTimeout":1000},"state":200},"remoteKey":"/112.128.4.100:51161"}
[2019-07-23 10:51:32.528] [Thread-22] [DEBUG] com.codingapi.txlcn.txmsg.netty.bean.SocketManager [133] - response is: MessageDto(action=init, groupId=null, data=InitClientParams(appName=tx-manager:8790, labelName=112.128.4.100:7005, dtxTime=36000, tmRpcTimeout=1000, seqLen=12, machineId=967), state=200)
[2019-07-23 10:51:32.582] [nioEventLoopGroup-4-7] [DEBUG] com.codingapi.txlcn.txmsg.netty.handler.RpcCmdDecoder [51] - cmd->{"msg":{"action":"ntm","data":{"host":"112.128.4.22","port":9700},"state":100},"remoteKey":"/112.128.4.100:51149"}
[2019-07-23 10:51:32.629] [nioEventLoopGroup-4-4] [DEBUG] com.codingapi.txlcn.txmsg.netty.handler.RpcCmdDecoder [70] - got response message[Netty Handler]
[2019-07-23 10:51:32.731] [tc-rpc-service-0] [DEBUG] com.codingapi.txlcn.tc.txmsg.ClientRpcAnswer [65] - Receive Message: MessageDto(action=ntm, groupId=null, data=NotifyConnectParams(host=112.128.4.22, port=9700), state=100)
[2019-07-23 10:51:32.830] [Thread-22] [DEBUG] com.codingapi.txlcn.txmsg.netty.impl.NettyRpcClient [83] - cmd request used time: 1397 ms
[2019-07-23 10:51:32.932] [tc-rpc-service-0] [DEBUG] com.codingapi.txlcn.txmsg.LCNCmdType [130] - parsed txmsg cmd: ntm
[2019-07-23 10:51:33.031] [Thread-21] [DEBUG] com.codingapi.txlcn.txmsg.netty.bean.NettyRpcCmd [54] - got response. 37592c5853c3537 
[2019-07-23 10:51:33.132] [tc-rpc-service-0] [DEBUG] com.codingapi.txlcn.tc.support.TxLcnBeanHelper [89] - getRpcBeanName->rpc_notify-connect
[2019-07-23 10:51:33.233] [Thread-22] [INFO ] com.codingapi.txlcn.tc.txmsg.TCSideRpcInitCallBack [92] - Finally, determined dtx time is 36000ms, tm rpc timeout is 1000 ms, machineId is 967
[2019-07-23 10:51:33.334] [tc-rpc-service-0] [INFO ] com.codingapi.txlcn.tc.txmsg.transaction.RpcNotifyConnectService [50] - transactionCmd->TransactionCmd(type=notifyConnect, requestKey=null, groupId=null, transactionType=null, msg=MessageDto(action=ntm, groupId=null, data=NotifyConnectParams(host=112.128.4.22, port=9700), state=100))
[2019-07-23 10:51:33.434] [Thread-21] [DEBUG] com.codingapi.txlcn.txmsg.netty.bean.SocketManager [133] - response is: MessageDto(action=init, groupId=null, data=InitClientParams(appName=tx-manager:8790, labelName=112.128.4.100:7005, dtxTime=36000, tmRpcTimeout=1000, seqLen=12, machineId=970), state=200)
[2019-07-23 10:51:33.636] [Thread-22] [INFO ] com.codingapi.txlcn.tc.txmsg.TMSearcher [111] - TM cluster's size: 3
[2019-07-23 10:51:33.737] [Thread-21] [DEBUG] com.codingapi.txlcn.txmsg.netty.impl.NettyRpcClient [83] - cmd request used time: 2405 ms
[2019-07-23 10:51:33.938] [Thread-21] [INFO ] com.codingapi.txlcn.tc.txmsg.TCSideRpcInitCallBack [92] - Finally, determined dtx time is 36000ms, tm rpc timeout is 1000 ms, machineId is 970
[2019-07-23 10:51:34.039] [Thread-21] [INFO ] com.codingapi.txlcn.tc.txmsg.TMSearcher [111] - TM cluster's size: 3
```

### 4. Tour Idea
可能是redis集群导致，以前使用单节点时没有出现过类似情况，另外，已注册的服务，在重启时，有时候在tx-manager里面会显示两条信息

**Comment by HongKing** [comment]
补充说明：关于已注册的服务在重启后，tx-manger中会显示两个的问题，我怀疑是心跳时间间隔的问题，服务重启在好点的服务器上是很快的，有可能正好在一个心跳间期重启完毕，那么tx-manager就会认为都是存活的，那么此时就出现两个的情况，其实其中一个是假的
