### ISSUE TITLE
com.codingapi.txlcn.txmsg.netty.impl.NettyRpcClient.remoteKeys 空指针异常

### ISSUE THREAD

**Issue by zlmisme** [codingapi/tx-lcn#495]
- [ ] I have searched the [issues](https://github.com/codingapi/tx-lcn/issues) of this repository and believe that this is not a duplicate.

### 1. Bug Description
java.lang.NullPointerException: null
	at com.codingapi.txlcn.txmsg.netty.bean.SocketManager.removeKeys(SocketManager.java:178) ~[txlcn-txmsg-netty-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
	at com.codingapi.txlcn.txmsg.netty.impl.NettyRpcClient.remoteKeys(NettyRpcClient.java:96) ~[txlcn-txmsg-netty-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
	at com.codingapi.txlcn.tm.core.SimpleTransactionManager.notifyTransaction(SimpleTransactionManager.java:130) ~[classes!/:5.0.2.RELEASE]
	at com.codingapi.txlcn.tm.core.SimpleTransactionManager.commit(SimpleTransactionManager.java:90) ~[classes!/:5.0.2.RELEASE]
	at com.codingapi.txlcn.tm.txmsg.transaction.NotifyGroupExecuteService.execute(NotifyGroupExecuteService.java:71) ~[classes!/:5.0.2.RELEASE]
	at com.codingapi.txlcn.tm.txmsg.ServerRpcAnswer.lambda$callback$0(ServerRpcAnswer.java:71) ~[classes!/:5.0.2.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_161]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_161]

### 2. Environment:
- JDK version: 1.8
- OS: linux
- TX-LCN version: 5.0.2.RELEASE
- Others:

### 3. Exception Stacktrace

```
Paste your Exception Stacktrace here!
```

**Comment by zlmisme** [comment]
我也遇到了相同的问题，请问大佬有解决方案吗
